c***********************************************************************
c
c   FILE NAME: menuinc.inc
c           This file only for winNT
c   CONTAINS:
c           This file define global variable for nccs_license
c
c     COPYRIGHT 1997 (c) Numerical Control Computer Sciences.
c           All Rights Reserved
c     MODULE NAME AND RELEASE LEVEL
c        menuinc.inc , 24.1
c     DATE AND TIME OF LAST  MODIFICATION
c        09/11/13 , 12:58:24
c
c***********************************************************************
      integer*4 ID_START
      parameter (ID_START = 100)

      integer*4 ID_SEARCH
      parameter (ID_SEARCH   = 201)
      integer*4 ID_ADD 
      parameter (ID_ADD = 202)
      integer*4 ID_DELETE
      parameter (ID_DELETE = 203)
      integer*4 ID_CLEAR
      parameter (ID_CLEAR = 204)
      integer*4 ID_COMPANY
      parameter (ID_COMPANY = 205)
      integer*4 ID_HARDW 
      parameter (ID_HARDW = 206)
      integer*4  ID_SOFTW
      parameter (ID_SOFTW = 207)
      integer*4 ID_OPT
      parameter (ID_OPT = 208)
      integer*4 ID_USER
      parameter (ID_USER = 209)
      integer*4 ID_LICTERM
      parameter (ID_LICTERM = 210)
      integer*4 ID_VERSION
      parameter (ID_VERSION = 211)
      integer*4 ID_SYSTEM
      parameter (ID_SYSTEM = 212)
      integer*4 ID_PASSWD
      parameter (ID_PASSWD = 213)
      integer*4 ID_EXIT
      parameter (ID_EXIT = 214)
      integer*4 ID_EDIT1
      parameter (ID_EDIT1 = 301)
      integer*4 ID_EDIT2
      parameter (ID_EDIT2 = 302)
      integer*4 ID_EDIT3
      parameter (ID_EDIT3 = 303)
      integer*4 ID_EDIT4
      parameter (ID_EDIT4 = 304)
      integer*4 ID_EDIT5
      parameter (ID_EDIT5 = 305)
      integer*4 ID_EDIT6
      parameter (ID_EDIT6 = 306)
      integer*4 ID_EDIT7
      parameter (ID_EDIT7 = 307)
      integer*4 ID_EDIT8
      parameter (ID_EDIT8 = 308)
      integer*4 ID_EDIT9
      parameter (ID_EDIT9 = 309)
      integer*4 ID_LOADFILE
      parameter (ID_LOADFILE = 310)
      character*80 INPUT_STRING
      parameter (INPUT_STRING = ' ' )

