c     File: Ptedpost.inc
c
c     COPYRIGHT 2000 (c) Numerical Control Computer Sciences.
c           All Rights Reserved
c      MODULE NAME AND RELEASE LEVEL
c			ptedpost.inc , 24.2
c     DATE AND TIME OF LAST  MODIFICATION
c			12/09/13 , 11:12:09        
c
      common /okposmp/ OKPOSMP
c
      integer*4 OKPOSMP(6000)
c
      common /bkposmp/ BKPOSMP
c
      integer*4 BKPOSMP(6000)
c
      common /oposmap/ OPOSMAP
      real*8 OPOSMAP(6000)
c
      common /bposmap/ BPOSMAP
      real*8 BPOSMAP(6000)
c
      common /ocposmp/ OCPOSMP
c
      character*1 OCPOSMP(16000)
c
      common /bcposmp/ BCPOSMP
c
      character*1 BCPOSMP(16000)
