/*********************************************************************
**
**    NAME         :  zkeysym.h
**
**       CONTAINS:
**       	User defined keyboard definitions.
**
**			WARNING:
**          Compile interface/zuserkeys.c to make changes in this file
**          effective.
**
**    COPYRIGHT 2000 (c) NCCS Inc.  All Rights Reserved.
**     MODULE NAME AND RELEASE LEVEL
**       zkeysym.h , 25.12
**    DATE AND TIME OF LAST  MODIFICATION
**       01/20/17 , 10:02:23
*********************************************************************/
/*
.....Number of valid keys to define
*/
#define NKEYSYMS 129
#define NFKEYSYMS 76
#define NBKEYSYMS 48
/*
.....Application types for keywords
*/
#define NOKEY  0
#define DASKEY 1
#define NISKEY 2
#define NCLKEY 3
#define CAMKEY 4
#define CADKEY 5
#define ALPHAKEY 6
#define MENUKEY 7
#define IPVKEY 8
#define MSLKEY 9
/*
.....Flag values for valid application keys
*/
#define NISFL 0x1
#define CAMFL 0x2
#define CADFL 0x4
#define SGNFL 0x8
#define DRWFL 0x10
#define SELFL 0x20
#define IPVFL 0x40
#define NCLIPVFL 0x100
#define EXECFL 0x8000
/*
.....Number of keywords for each application
*/
#define NDASKEYS 40
#define NNISKEYS 77
#define NNCLKEYS 18
#define NCAMKEYS 418
#define NCADKEYS 225
#define NIPVKEYS 101
#define NMSLKEYS 20
/*
......total functions include NDASKEYS,
......NNISKEYS, NNCLKEYS, NCAMKEYS, NCADKEYS
......Apparently not used IJD 25-May-2001
*/
/* #define NTOTALFUNC	843 */
#define UZ_MAX_MENUITEM	2000
/*
.....maxinum of status button name
*/
#define UZ_MAX_STATNAME 100
/*
.....maxinum function tie to one status name
*/
#define MAX_STAT_FUNC 10
/*
......for accelerator key on WinNT
*/	
#define UZ_MAX_KEYITEM	1000	
/*
......this value must be the same as UDM_MAX_MENU
*/
#define UZ_MAX_MENU	200
/*
.....Keyword definition structure
*/
typedef struct
{
	char *name;
	int type;
	int sub;
	unsigned short app;
	char *descrip;
} UZ_keycalls;

typedef struct
{
/*
.....status name
*/
	char *name;
/*
.....status index
*/
	int sub;
/*
.....default function for status name
.....it will use function input by user if
.....the status button (UDM_menu_struc) have
.....a valid "file" (function)
*/
	char *func;
} UZ_statcalls;
/*
.....Programmed keys structure
*/
typedef struct
{
	int type;
	int sub;
	short flag;
/*
.....added a string to store menu name (added menu into key)
.....Yurong
*/
	char name[30];
/*
.....added function parameter
.....Yurong 11/27/00
*/
	char *params;
} UZ_keytable;

typedef struct
{
/*
......parameter to pass in function name
*/
	char *params;
/*
......function name
*/
	char fname[30];
/*
......parameter to pass in function description
*/
	char descrip[40];
} UZ_functable;

#ifdef ZKEYSYM

/*
.....added for WinNT
.....now I only use one function per button (menu)
.....may used an arrany of them later
*/
UZ_functable UZ_itemcalls[UZ_MAX_MENUITEM];
int UZ_item_count = 0;
UZ_functable UZ_accelcalls[UZ_MAX_KEYITEM];
int UZ_accel_count = 0;
int UZ_menucalls[UZ_MAX_MENU];
int UZ_menu_count = 0;
char UZ_mouse_function[20][80];
/*
.....Valid function key definitions
*/
char *zfkeysym[] =
{
	"pause", "scroll_lock", "multi_key", "home", "prior", "next", "end",
	"select", "print", "execute", "insert", "undo", "find", "cancel",
	"help", "break", "num_lock",

	"kp_space", "kp_tab", "kp_enter", "kp_f1", "kp_f2", "kp_f3", "kp_f4",
	"kp_equal", "kp_multiply", "kp_add", "kp_separator", "kp_subtract",
	"kp_decimal", "kp_divide", "kp_0", "kp_1", "kp_2", "kp_3", "kp_4",
	"kp_5", "kp_6", "kp_7", "kp_8", "kp_9",

	"f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10",
	"f11", "f12", "f13", "f14", "f15", "f16", "f17", "f18", "f19", "f20",
	"f21", "f22", "f23", "f24", "f25", "f26", "f27", "f28", "f29", "f30",
	"f31", "f32", "f33", "f34", "f35"
};
/*
.....Valid button and dial defintions
*/
char *zbkeysym[] =
{
	"BUTTON_1", "BUTTON_2", "BUTTON_3", "BUTTON_4", "BUTTON_5",
	"BUTTON_6", "BUTTON_7", "BUTTON_8", "BUTTON_9", "BUTTON_10",
	"BUTTON_11", "BUTTON_12", "BUTTON_13", "BUTTON_14", "BUTTON_15",
	"BUTTON_16", "BUTTON_17", "BUTTON_18", "BUTTON_19", "BUTTON_20",
	"BUTTON_21", "BUTTON_22", "BUTTON_23", "BUTTON_24", "BUTTON_25",
	"BUTTON_26", "BUTTON_27", "BUTTON_28", "BUTTON_29", "BUTTON_30",
	"BUTTON_31", "BUTTON_32",

	"DIAL_1_LEFT", "DIAL_1_RIGHT", "DIAL_2_LEFT", "DIAL_2_RIGHT",
	"DIAL_3_LEFT", "DIAL_3_RIGHT", "DIAL_4_LEFT", "DIAL_4_RIGHT",
	"DIAL_5_LEFT", "DIAL_5_RIGHT", "DIAL_6_LEFT", "DIAL_6_RIGHT",
	"DIAL_7_LEFT", "DIAL_7_RIGHT", "DIAL_8_LEFT", "DIAL_8_RIGHT"
};
/*
.....Valid key calls
*/
UZ_keytable UZ_niskeytab[NKEYSYMS*3],UZ_nisfkeytab[NFKEYSYMS*3];
UZ_keytable UZ_camkeytab[NKEYSYMS*3],UZ_camfkeytab[NFKEYSYMS*3];
UZ_keytable UZ_cadkeytab[NKEYSYMS*3],UZ_cadfkeytab[NFKEYSYMS*3];
UZ_keytable UZ_ipvkeytab[NKEYSYMS*3],UZ_ipvfkeytab[NFKEYSYMS*3];
/*
UZ_keytable UZ_nisbkeytab[NBKEYSYMS],UZ_cambkeytab[NBKEYSYMS];
UZ_keytable UZ_cadbkeytab[NBKEYSYMS],UZ_ipvbkeytab[NBKEYSYMS];
*/
UZ_keytable UZ_nisbkeytab[NBKEYSYMS],UZ_cambkeytab[NFKEYSYMS*3];
UZ_keytable UZ_cadbkeytab[NBKEYSYMS],UZ_ipvbkeytab[NFKEYSYMS*3];
/*
.....Valid DAS call strings
*/
char *UZ_daskey[] =
{
	"\\tuton", "\\tutoff", "\\deletelast", "!tog", "\\recon", "\\playb",
	"\\recoff", "\\prompt", "\\echo", "\\blin", "\\help", "\\panic",
	"\\elin", "\\\\0", "\\\\1", "\\\\2", "\\\\3", "\\\\4", "\\\\6",
	"\\\\7", "\\\\8", "\\\\9", "\\\\A", "\\\\B", "\\\\C", "\\\\D",
	"\\\\E", "\\\\F", "\\\\G", "\\\\H", "\\\\I", "\\\\J", "\\\\K",
	"\\drafting", "\\calc", "\\pause", "\\resume",/* "\\\\L", "\\\\M", */
	"\\dellin", "\\inslin", "\\actln"
};
/*
.....Programmable key word definitions
*/
UZ_keycalls UZ_keyfuncs[] =
{
	{"KEY_TUTON",DASKEY,0,0x17, "Tutorials On"}, 
	{"KEY_TUTOFF",DASKEY,1,0x17, "Tutorials Off"},
	{"KEY_DELLAST",DASKEY,2,0x14, "Delete Last Entity"}, 
	{"KEY_PIKLOC",DASKEY,3,0x16, "Toggle to PICK/LOCATOR mode"},
	{"KEY_RECON",DASKEY,4,0x17,"Start Recording"}, 
	{"KEY_PLAYBACK",DASKEY,5,0x17,"Start Playback"},
	{"KEY_RECOFF",DASKEY,6,0x17,"Stop Recording"}, 
	{"KEY_RECPRM",DASKEY,7,0x17,"Record Prompt for Input"},
	{"KEY_RECMSG",DASKEY,8,0x17,"Record User Message"}, 
	{"KEY_BLINE",DASKEY,9,0x17,"Move the cursor to the beginning of the command line"},
	{"KEY_HELP",DASKEY,10,0x17,"Display Help for Prompt"}, 
	{"KEY_PLAYSTOP",DASKEY,11,0x17,"Stop Playback"},
	{"KEY_ELINE",DASKEY,12,0x17,"Move the cursor to the end of the command line"},
	{"KEY_ROOT",DASKEY,13,0x17,"Go to Root"},
	{"KEY_REJLST",DASKEY,14,0x17,"Reject Last Operation"}, 
	{"KEY_DONE",DASKEY,15,0x1f,"Accept operation (Done)"},
	{"KEY_REJECT",DASKEY,16,0x17,"Reject Operation"}, 
	{"KEY_RSTCHAR",DASKEY,17,0x17,"Restore Character"},
	{"KEY_DEFVAL",DASKEY,18,0x16,"Accept Default"}, 
	{"KEY_BSPACE",DASKEY,19,0x17,"Backspace Character"},
	{"KEY_ALTACT",DASKEY,20,0x16,"Alternate Action"}, 
	{"KEY_SELECT",DASKEY,21,0x16,"Enable Selection Filter"},
	{"KEY_PICK",DASKEY,22,0x16,"Toggle to PICK mode"}, 
	{"KEY_LOCATE",DASKEY,23,0x16,"Toggle to LOCATOR mode"},
	{"KEY_VALUATOR",DASKEY,24,0x16,"Toggle to VALUATOR mode"}, 
	{"KEY_TEXT",DASKEY,25,0x16,"Toggle to TEXT mode"},
	{"KEY_CHOICE",DASKEY,26,0x16,"Toggle to CHOICE Mode"}, 
	{"KEY_PANIC",DASKEY,27,0x17,"Panic Stop"},
	{"KEY_UPFIELD",DASKEY,28,0x1f,"UP Arrow"}, 
	{"KEY_DNFIELD",DASKEY,29,0x1f,"Down Arrow"},
	{"KEY_CLEAR",DASKEY,30,0x1f,"Clear Field"}, 
	{"KEY_TOGGLE",DASKEY,31,0x1f,"Toggle field"},
	{"KEY_EXITSUB",DASKEY,32,0x17,"Exit Subsystem"}, 
	{"CAD_DRAFT",DASKEY,33,0x17,"Enter Drafting Mode"},
	{"CAD_CALC",DASKEY,34,0x14,"Calculator"}, 
	{"KEY_PLAYPAUSE",DASKEY,35,0x17,"Pause Playback"},
	{"KEY_PLAYRESUM",DASKEY,36,0x17, "Resume Playback"}, 
	{"KEY_DELETE_LINE",DASKEY,37,0x17, "Delete a line in Multi-Command Window"}, 
	{"KEY_INSERT_LINE",DASKEY,38,0x17, "Insert a line in Multi-Command Window"}, 
	{"KEY_ACTIVE_LINE",DASKEY,39,0x17, "Set the active Line in Multi-Command Window"},
	{"KEY_FUNCTION",NISKEY,0,0x117, "Select Function Key"},
	{"NIS_LOAD_KEYDEF",NISKEY,1,0x17,"Load Key Definition File"},
	{"DUMMY",NISKEY,2,0x17,"No description"},
	{"DUMMY",NISKEY,3,0x17,"No description"},
	{"DUMMY",NISKEY,4,0x17,"No description"}, 
	{"DUMMY",NISKEY,5,0x17,"No description"},
	{"DUMMY",NISKEY,6,0x17,"No description"}, 
	{"DUMMY",NISKEY,7,0x17,"No description"},
	{"KEY_CAPTURE_TOGGLE",NISKEY,8,0x17,"Toggle Window Capture"}, 
	{"NIS_SYSTEM_ENTER",NISKEY,9,0x117,"Enter Operating System"},
	{"NIS_SYSTEM_ONCE",NISKEY,10,0x117,"One Shot Operating System"}, 
	{"NIS_SYSTEM_MENU",NISKEY,11,0x17,"Operating System Menu"},
	{"NIS_QUE_MODALS",NISKEY,12,0x17,"NCL Que Modals"}, 
	{"NIS_NCL_QUE",NISKEY,13,0x17,"NCL Batch Que"},
	{"NIS_UTIL_QUE",NISKEY,14,0x17,"Utility Batch Que"}, 
	{"NIS_DISPLAY_NCLQUE",NISKEY,15,0x17,"Display NCL Que"},
	{"NIS_DISPLAY_UTILQUE",NISKEY,16,0x17,"Display Utility Que"}, 
	{"NIS_NCL_BATCH",NISKEY,17,0x17,"Run NCL Batch"},
	{"NIS_UTIL_BATCH",NISKEY,18,0x17,"Run Utility Batch"}, 
	{"NIS_BATCH_ONCE",NISKEY,19,0x17,"One Shot Utility Batch"},
	{"NIS_DISPLAY_BATLOG",NISKEY,20,0x17,"Display Batch Log"}, 
	{"NIS_BATCH_STATUS",NISKEY,21,0x17,"Show Batch Status"},
	{"NIS_COPY_FILE",NISKEY,22,0x17,"Copy a File"}, 
	{"NIS_RENAME_FILE",NISKEY,23,0x17,"Rename a File"},
	{"NIS_DELETE_FILE",NISKEY,24,0x17,"Delete a File"}, 
	{"NIS_PURGE_FILE",NISKEY,25,0x17,"Purge files"},
	{"NIS_IFACE_MODALS",NISKEY,26,0x117,"Interface Modals"}, 
	{"NIS_MODALS_OUTPUT",NISKEY,27,0x17,"Control Output of Modals Files"},
	{"NIS_TOOLIB",NISKEY,28,0x17,"Run TOOLIB Utility"}, 
	{"NIS_EDIT_MENUAREA",NISKEY,29,0x17,"Add/Delete Menu Area"},
	{"NIS_PRINT_SCREEN",NISKEY,30,0x17,"Print Current Screen"}, 
	{"NIS_DISPLAY_MODALS",NISKEY,31,0x17,"Display File Modals"},
	{"NIS_DISPLAY_CURRENT",NISKEY,32,0x17,"Display Cerrent PP File"}, 
	{"NIS_DISPLAY_PR",NISKEY,33,0x17,"Display Current Print File"},
	{"NIS_DISPLAY_PR1",NISKEY,34,0x17,"Display Current PR1 File"}, 
	{"NIS_DISPLAY_PU1",NISKEY,35,0x17,"Display Current PU1 File"},
	{"NIS_DISPLAY_FILE",NISKEY,36,0x17,"Display by Filename"}, 
	{"NIS_EDIT_CURRENT",NISKEY,37,0x17,"Edit Current PP File"},
	{"NIS_EDIT_PR",NISKEY,38,0x17,"Edit Current Print File"}, 
	{"NIS_EDIT_PR1",NISKEY,39,0x17,"Edit Current PR File"},
	{"NIS_EDIT_PU1",NISKEY,40,0x17,"Edit Current PU1 File"}, 
	{"NIS_EDIT_FILE",NISKEY,41,0x17,"Edit by filename"},
	{"NIS_PRINT_CURRENT",NISKEY,42,0x17,"Print Current PP File"}, 
	{"NIS_PRINT_PR",NISKEY,43,0x17,"Print Current Print File"},
	{"NIS_PRINT_PR1",NISKEY,44,0x17,"Print Current PR1 File"}, 
	{"NIS_PRINT_PU1",NISKEY,45,0x17,"Print Current PU1 File"},
	{"NIS_PRINT_FILE",NISKEY,46,0x17,"Print by Filename"}, 
	{"NIS_PRINT_STATUS",NISKEY,47,0x17,"Show Print Que"},
	{"NIS_PLOT_DRAWING",NISKEY,48,0x17,"Plot Drawing File"},
	{"NIS_PLOT_MODAL",NISKEY,49,0x17,"Offline Plot Modals"},
	{"NIS_PLOT_FILE",NISKEY,50,0x17,"Offline Plot Routines"}, 
	{"NIS_POST_MACHINE",NISKEY,51,0x17,"Post by MACHIN Card"},
	{"NIS_POST_FILE",NISKEY,52,0x17,"Post by Filename"}, 
	{"NIS_POST_BATCH",NISKEY,53,0x17,"Post in Batch"},
	{"NIS_UTIL_FILE",NISKEY,54,0x17,"Run Utility against File"}, 
	{"NIS_UTIL_BATCH",NISKEY,55,0x17,"Run Utility Batch"},
	{"NIS_TAPE_MODALS",NISKEY,56,0x17,"NC Tape Modals"}, 
	{"NIS_DNC_MODALS",NISKEY,57,0x17,"DNC Modals"},
	{"NIS_PUNCH_TAPE",NISKEY,58,0x17,"Punch NC Tape"}, 
	{"NIS_PUNCH_BATCH",NISKEY,59,0x17,"Punch NC Tape in Batch"},
	{"NIS_READ_TAPE",NISKEY,60,0x17,"Read NC Tape"}, 
	{"NIS_READ_TAPE_BATCH",NISKEY,61,0x17,"Read NC Tape in Batch"},
	{"NIS_VFY_TAPE",NISKEY,62,0x17,"Verify NC Tape"}, 
	{"NIS_VFY_TAPE_BATCH",NISKEY,63,0x17,"Verify NC Tape in Batch"},
	{"NIS_DNC",NISKEY,64,0x17,"Run DNC Utility"}, 
	{"NIS_DNC_BATCH",NISKEY,65,0x17,"Run DNC Utility in Batch"},
	{"NIS_IGES",NISKEY,66,0x17,"Run IGES Utility"}, 
	{"NIS_VDA",NISKEY,67,0x17,"Run VDA Utility"},
	{"NIS_MCV",NISKEY,68,0x17,"Run MCV Utility"}, 
	{"NIS_MPT",NISKEY,69,0x17,"Run MPT Utility"},
	{"NIS_QCV",NISKEY,70,0x17,"Run QCV Utility"}, 
	{"NIS_NMG",NISKEY,71,0x17,"Run NMG Utility"},
	{"NIS_DCNV",NISKEY,72,0x17,"Run DCNV Utility"},
	{"NIS_LOAD_LAYOUT", NISKEY, 73, 0x17,"Load Layout file"},
	{"NIS_SAVE_LAYOUT",NISKEY,74,0x17,"Save layout file"},
	{"NIS_MENU_DESIGN", NISKEY, 75, 0x117,"Design menu"},
	{"NIS_LOAD_MOUSE", NISKEY, 76, 0x17,"Load Mouse Definition file"},

	{"NCL_UNIBASE_MODALS",NCLKEY,0,0x7,"Unibase Save Modals"},
	{"NCL_REPAINT_FULL",NCLKEY,1,0x17,"Full Screen Repaint"},
	{"NCL_REPAINT_VIEW",NCLKEY,2,0x7,"Repaint View"},
	{"NCL_VIEW_NEGX",NCLKEY,3,0x6,"View along negative X-axis"},
	{"NCL_VIEW_NEGY",NCLKEY,4,0x6,"View along negative Y-axis"}, 
	{"NCL_VIEW_NEGZ",NCLKEY,5,0x6,"View along negative Z-axis"},
	{"NCL_FLIP_VIEW",NCLKEY,6,0x6,"View from opposite dir"},
	{"NCL_LABEL_ON",NCLKEY,7,0x16,"Display Selected Label"},
	{"NCL_GRID_OFF",NCLKEY,8,0x16,"Turn off Grid"}, 
	{"NCL_GRID_ON",NCLKEY,9,0x16,"Grid Activate Form"},
	{"NCL_INVIS",NCLKEY,10,0x16,"Invisible Entities"}, 
	{"NCL_CHG_COLOR",NCLKEY,11,0x16,"Change default Color"},
	{"NCL_SET_LAYER",NCLKEY,12,0x16,"Set Layer Number"}, 
	{"NCL_MOD_ATTR",NCLKEY,13,0x16,"Modify Attribute Form"},
	{"KEY_NOOP",NCLKEY,14,0x1f,"No operation"},
	{"NCL_LINE_STYLE",NCLKEY,15,0x16,"Set Default Line Style"},
	{"NCL_PICK_APERTURE",NCLKEY,16,0x16,"Change Pick Aperture"}, 
	{"NCL_VISIBLE",NCLKEY,17,0x16, "No description available"},
	{"NCL_LABEL_OFF",NCLKEY,18,0x16,"Erase Selected Labels"}, 
	{"NCL_PICK_MARK",NCLKEY,19,0x16,"Choose Pick Marker"},
	{"NCL_LIMIT_GEO",NCLKEY,20,0x16,"Limit Pickable Geo Types"}, 
	{"NCL_DYNAMIC_CENTER",NCLKEY,21,0x16,"Dynamic View Center"},
	{"NCL_VERIFY_TOGGLE",NCLKEY,22,0x16,"Toggle Verify Mode"},
	{"NCL_LOAD_VIEW",NCLKEY,23,0x6,"Load View"},
	{"NCL_UNTRIM",NCLKEY,24,0x6,"Untrim geometry"},
	{"NCL_CHANGE_VIEW",NCLKEY,25,0x6,"Change View Form"}, 
	{"NCL_FIT_VIEW",NCLKEY,26,0x16,"Extrema Zoom"},
	{"NCL_PAN",NCLKEY,27,0x16,"Pan View"}, 
	{"NCL_PREVIOUS_VIEW",NCLKEY,28,0x16,"Previous View"},
	{"NCL_WINDOW_ZOOM",NCLKEY,29,0x16,"Window Zoom"}, 
	{"NCL_SCALE_ZOOM",NCLKEY,30,0x16,"Scale Zoom"},
	{"NCL_RESET_VIEW",NCLKEY,31,0x16,"Reset View"}, 
	{"NCL_SAVE_VIEW",NCLKEY,32,0x6,"Save View"},
	{"NCL_SCALE_VIEW",NCLKEY,33,0x16,"Scale View"}, 
	{"NCL_SCREEN_SELECT",NCLKEY,34,0x6,"Select a screen format"},
	{"NCL_CALCULATOR",NCLKEY,35,0x6,"Open Calculator"},
	{"NCL_LBL_LDR_ON",NCLKEY,36,0x6,"Display Leader lines for selected Labels"},
	{"NCL_LBL_LDR_OFF",NCLKEY,37,0x6,"Erase Leader lines for selected Labels"},
	{"NCL_LABEL_OVERLAP",NCLKEY,38,0x6,"Position Labels with Minimal Overlap"},
	{"NCL_LABEL_RESET",NCLKEY,39,0x6,"Reset all Labels to their Default position"}, 
	{"NCL_SAVE_VIEWFMT",NCLKEY,40,0x6,"Save Displayed View"},
	{"NCL_DYNAMIC_MOUSE",NCLKEY,41,0x16,"Dynamic Mouse Viewing"},
	{"NCL_DELETE_VIEW",NCLKEY,42,0x6,"Delete View"},
	{"NCL_VIEW_X",NCLKEY,43,0x6,"View along x-axis"}, 
	{"NCL_VIEW_Y",NCLKEY,44,0x6,"View along y-axis"},
	{"NCL_VIEW_Z",NCLKEY,45,0x6,"View along z-axis"}, 
	{"NCL_VIEW_TRACUT",NCLKEY,46,0x2,"View By TRACUT Matrix"},
	{"NCL_VIEW_REFSYS",NCLKEY,47,0x2,"View By REFSYS Matrix"}, 
	{"NCL_VIEW_MATRIX",NCLKEY,48,0x2,"View by Matrix"},
	{"NCL_DYNAMIC_ZOOM",NCLKEY,49,0x106,"Dynamic Zoom"}, 
	{"NCL_DYNAMIC_PAN",NCLKEY,50,0x106,"Dynamic Pan"},
	{"NCL_DYNAMIC_UNZOOM",NCLKEY,51,0x106,"Reset View"}, 
	{"NCL_XPAN_LEFT",NCLKEY,52,0x8116,"immediate PAN Left"},
	{"NCL_XPAN_RIGHT",NCLKEY,53,0x8116,"immediate PAN Right"},
	{"NCL_YPAN_LEFT",NCLKEY,54,0x8116,"immediate PAN Down"},
	{"NCL_YPAN_RIGHT",NCLKEY,55,0x8116,"immediate PAN Up"}, 
	{"NCL_XROT_LEFT",NCLKEY,56,0x8106,"Immediate Rotate X Left"},
	{"NCL_XROT_RIGHT",NCLKEY,57,0x8106,"Immediate Rotate X Right"}, 
	{"NCL_YROT_LEFT",NCLKEY,58,0x8106,"Immediate Rotate Y Left"},
	{"NCL_YROT_RIGHT",NCLKEY,59,0x8106,"Immediate Rotate Y Right"}, 
	{"NCL_ZROT_LEFT",NCLKEY,60,0x8106,"Immediate Rotate Z Left"},
	{"NCL_ZROT_RIGHT",NCLKEY,61,0x8106,"Immediate Rotate Z Right"}, 
	{"NCL_ZOOM_DOWN",NCLKEY,62,0x8116,"immediate  Zoom Out"},
	{"NCL_ZOOM_UP",NCLKEY,63,0x8116,"immediate Zoom In"}, 
	{"NCL_TVIEW_DOWN",NCLKEY,64,0x8006,"Toggle Current Vport Down"},
	{"NCL_TVIEW_UP",NCLKEY,65,0x8006,"Toggle Current Vport Up"}, 
	{"NCL_DYNAMIC_XYROT",NCLKEY,66,0x106,"Dynamic XY-Rotation"},
	{"NCL_DYNAMIC_TUMBLE",NCLKEY,67,0x106,"Dynamic Tumble"}, 
	{"NCL_DYNAMIC_ZROT",NCLKEY,68,0x106,"Dynamic Z_Rotation"},
	{"NCL_DYNAMIC_VCROT",NCLKEY,69,0x106,"Dynamic Vector Rotation"}, 
	{"NCL_DYNAMIC_MODALS",NCLKEY,70,0x106,"Dynamic View Modals"},
	{"NCL_EXIT",NCLKEY,71,0x8006,"Exit NCL"}, 
	{"NCL_REDISP_GEO",NCLKEY,72,0x16,"Redisplay Entities"}, 
	{"NCL_SET_ATTRIBS",NCLKEY,73,0x16,"Set Geometry Attributes"}, 
	{"NCL_NAME_MODALS",NCLKEY,74,0x6,"Set Geometry Naming Modals"},
	{"NCL_INPUT_LAYER",NCLKEY,75,0x6,"Set Input Layer"}, 
	{"NCL_LAYERS",NCLKEY,76,0x6,"Layer Management"},
	{"NCL_DISPLAY_BUFFER",NCLKEY,77,0x6,"Display Buffer Settings"}, 
	{"NCL_MISC_MODALS",NCLKEY,78,0x16,"Miscellaneous Modals Form"},
	{"NCL_PICK_MODALS",NCLKEY,79,0x6,"Pick Modals Form"}, 
	{"NCL_SET_INCH",NCLKEY,80,0x6,"Set Units to inch"},
	{"NCL_SET_MM",NCLKEY,81,0x6,"Set Units to Millimeters"}, 
	{"NCL_ENTITY_DATA",NCLKEY,82,0x16,"Geometric Entity Data"},
	{"NCL_RESTART",NCLKEY,83,0x6,"Restart NCL"},
	{"NCL_INVISIBLE_GEO",NCLKEY,84,0x16,"Invisible Geometry"}, 
	{"NCL_INVISIBLE_ALL",NCLKEY,85,0x16,"Invisible All displayed"},
	{"NCL_VISIBLE_GEO",NCLKEY,86,0x16,"Visible Entities"}, 
	{"NCL_VISIBLE_ALL",NCLKEY,87,0x16,"Visible All Entities"},
	{"NCL_MODIFY_ATTRIBS",NCLKEY,88,0x16,"Modify Geometry Attributes"}, 
	{"NCL_TRIM_EXTEND",NCLKEY,89,0x16,"Trim/extend Geometry"},
	{"NCL_MID_TRIM",NCLKEY,90,0x16,"Mid-Trim Geometry"}, 
	{"NCL_RENAME_GEO",NCLKEY,91,0x16,"No description availabel"},
	{"NCL_LABEL_ALTER",NCLKEY,92,0x16,"Alter Label Locations"},
	{"NCL_MDAXIS_ON",NCLKEY,93,0x6,"Display Modelling Axis"}, 
	{"NCL_MDAXIS_OFF",NCLKEY,94,0x6,"Invisible Modelling Axis"},
	{"NCL_WPAXIS_ON",NCLKEY,95,0x6,"Display Work plane Axis"}, 
	{"NCL_WPAXIS_OFF",NCLKEY,96,0x6,"Invisible Work Plane Axis"},
	{"NCL_MDAXIS_RESET",NCLKEY,97,0x6,"Reset Modelling Axis"}, 
	{"NCL_WPAXIS_RESET",NCLKEY,98,0x6,"Reset Work Plane Axis"},
	{"NCL_GRID_ACT",NCLKEY,99,0x16,"Activate Grid"}, 
	{"NCL_GRID_INACT",NCLKEY,100,0x16,"Inactivate Grid"},
	{"NCL_MDAXIS_ALIGN",NCLKEY,101,0x6,"Align Model Axis to Vport"}, 
	{"NCL_MDAXIS_ORIG",NCLKEY,102,0x6,"Set Modelling Axis Origin"},
	{"NCL_MDAXIS_AXIS",NCLKEY,103,0x6,"Set Modelling Axis Axes"},
	{"NCL_MDAXIS_SNAP",NCLKEY,104,0x6,"Snap Modelling Axis to Axis"},
	{"NCL_MDAXIS_ROT",NCLKEY,105,0x6,"Rotate Modelling Axis"}, 
	{"NCL_WPAXIS_ALIGN",NCLKEY,106,0x6,"Align WP Axis to Vport"},
	{"NCL_WPAXIS_ORIG",NCLKEY,107,0x6,"Set Work Plane Axis Origin"}, 
	{"NCL_WPAXIS_AXIS",NCLKEY,108,0x6,"Set Work Plane Axis Axes"},
	{"NCL_WPAXIS_SNAP",NCLKEY,109,0x6,"Snap WP Axis to Axis"},
	{"NCL_WPAXIS_PLANE",NCLKEY,110,0x6,"Snap WP Axis to Plane"},
	{"NCL_WPAXIS_ROT",NCLKEY,111,0x6,"Rotate Work Plane Axis"},
	{"NCL_SELECT_SINGLE",NCLKEY,112,0x20,"Single Geometry Selection"}, 
	{"NCL_SELECT_CHAIN",NCLKEY,113,0x20,"Chain Geometry Selection "},
	{"NCL_SELECT_ALL",NCLKEY,114,0x20,"Select all geometry"}, 
	{"NCL_SELECT_GEO",NCLKEY,115,0x20,"Select  Geometry Types"},
	{"NCL_SELECT_CHMOD",NCLKEY,116,0x20,"Chain Select Modals"}, 
	{"NCL_SELECT_REGIN",NCLKEY,117,0x20,"Region in  Selection"},
	{"NCL_SELECT_REGOUT",NCLKEY,118,0x20,"Region out Selection"},
	{"NCL_SELECT_REGINX",NCLKEY,119,0x20,"Region in Cross Selection"},
	{"NCL_SELECT_REGOUTX",NCLKEY,120,0x20,"Region out Cross Selection"},
	{"NCL_SELECT_REJECT",NCLKEY,121,0x20,"Reject Geometry Selection"},
	{"NCL_SELECT_UNLAST",NCLKEY,122,0x20,"Deselect Last"}, 
	{"NCL_SELECT_UNALL",NCLKEY,123,0x20,"Deselect All"},
	{"NCL_SELECT_FILT",NCLKEY,124,0x20,"Set Selection Filter"},
	{"NCL_SELECT_FSING",NCLKEY,125,0x20,"Select Filtered Single"},
	{"NCL_SELECT_FCHN",NCLKEY,126,0x20,"Select Filtered Chain"}, 
	{"NCL_SELECT_FALL",NCLKEY,127,0x20,"Select Filtered All"},
	{"NCL_SELECT_FREGIN",NCLKEY,128,0x20,"Select Filtered Region in"}, 
	{"NCL_SELECT_FREGOUT",NCLKEY,129,0x20,"Select Filtered Region out"},
	{"NCL_SELECT_FREGINX",NCLKEY,130,0x20,"Select Filt Region in Cross"},
	{"NCL_SELECT_FREGOUTX",NCLKEY,131,0x20,"Select Filt Region out Cross"},
	{"NCL_MIN_MENU",NCLKEY,132,0x17,"Minimize menus only"}, 
	{"NCL_MIN_ALL",NCLKEY,133,0x17,"Minimize Menus and graphic"},
	{"NCL_LABEL_MODALS", NCLKEY, 134, 0x8006,"Label Modals"},
	{"NCL_ENTITY_ATTRIB",NCLKEY,135, 0x16,"Geometric Entity Attribute"},
	{"NCL_SHADE_ENTITY",NCLKEY,136, 0x6,"Shade Entity"}, 
	{"NCL_UNSHADE_ENTITY",NCLKEY,137, 0x6,"Unshade Entity"},
	{"NCL_ANALYZE_SURF",NCLKEY,138, 0x6,"Analyze Surface"}, 
	{"NCL_ANALYZE_SURF_THRU",NCLKEY,139, 0x6,"Analyze Surfaces"},
	{"NCL_VIEW_TOOL",NCLKEY,140,0x2,"View Down Tool Axis"},
	{"NCL_SELECT_MODE",NCLKEY,141,0x17,"NCLCAM or DRAWING"},
	{"NCL_UNITS",NCLKEY,142,0x17,"Set Model Units"},
	{"NCL_ANALYZE_GEO",NCLKEY,143, 0x6,"Analyze Geometry"}, 
	{"NCL_PAN_TOGGLE",NCLKEY,144, 0x106,"Translation On/Off"},
	{"NCL_ROTATE_TOGGLE",NCLKEY,145, 0x106,"Ratation On/Off"},
	{"NCL_DOMINATE_TOGGLE",NCLKEY,146, 0x106,"Dominate Mode On/Off"},
	{"NCL_GAIN_DOWN",NCLKEY,147, 0x106,"Sensitivity Down"},
	{"NCL_GAIN_UP",NCLKEY,148, 0x106,"Sensitivity Up"},
	{"NCL_GAIN_DEFAULT",NCLKEY,149, 0x106,"Default Sensitivity"},
	{"NCL_TOGGLE_SPACEMOUSE",NCLKEY,150, 0x6,"Toggle SpaceMouse Usage"},
	{"NCL_VIEW_WIREFRAME",NCLKEY,151, 0x6,"Wireframe View"},
	{"NCL_VIEW_SHADED",NCLKEY,152, 0x6,"Shaded View"},
	{"NCL_VIEW_HIDDEN",NCLKEY,153, 0x6,"Hidden Line View"},
	{"NCL_VIEW_SHADED_ONLY",NCLKEY,154, 0x6,"Shaded Only View"},
	{"NCL_SAVE_SESSION",NCLKEY,155, 0x17,"Save NCL Session"},
	{"NCL_LOAD_SESSION",NCLKEY,156, 0x17,"Load NCL Session"},
	{"NCL_SELECT_SFCHAIN",NCLKEY,157, 0x20,"Chain Surface Selection"},
	{"NCL_COLOR_MODALS",NCLKEY,158, 0x8006,"Geometry Color Modals"},
	{"NCL_BACKGROUND",NCLKEY,159, 0x8006,"Display Background Modals"},
	{"NCL_OPEN_FILE",NCLKEY,160, 0x8006,"Open File"},
	{"NCL_UPDATE_TIME",NCLKEY,161, 0x8006,"Update the Elapsed Time"},
	{"NCL_NEW_SESSION",NCLKEY,162, 0x8006,"Spawn a NCL subprocess"},
	{"NCL_EDGE_OFF_ALL",NCLKEY,163, 0x8006,"Turn Off Edges for All Surfaces"},
	{"NCL_EDGE_ON_ALL",NCLKEY,164, 0x8006,"Turn On Edges for All Surfaces"},
	{"NCL_SELECT_CLIP",NCLKEY,165, 0x20,"Display filter bounding region form"},
   {"NCL_SWAP_VIEW",NCLKEY,166,0x1f,"Swap Invisible/Visible Views"},
   {"NCL_SWAP_ENTITIES",NCLKEY,167,0x1f,"Swap Invis/Vis Entities"},
   {"NCL_LOAD_COLORS",NCLKEY,168,0x1f,"Load an External Color File"},
   {"NCL_MERGE_COLORS",NCLKEY,169,0x1f,"Merge an External Color File"},
	{"KEY_PICK_LOCATE",NCLKEY,170,0x1f,"Perform Standard Mouse Function"},
	{"NCL_RESET_SPACEMOUSE",NCLKEY,171,0x1f,"Reset the SpaceMouse driver"},
	{"NCL_FORM_DESIGN",NCLKEY,172,0x1f,"Interactive form design"},
	{"NCL_UNIBASE_STAT",NCLKEY,173,0x1f,"Unibase Createion Statistics"},
	{"NCL_AUTOSAVE_FORM",NCLKEY,174,0x1f,"Display Autosave Form"},

	{"CAM_RENAME_GEO",CAMKEY,0,0x2,"Rename Geometry (w/source)"},
	{"CAM_TEXT_MODE",CAMKEY,1,0x2,"Set Input Mode"},
	{"DUMMY",CAMKEY,2,0x2,"Not Used"},
	{"DUMMY",CAMKEY,3,0x2,"Not Used"},
	{"CAM_ARCSLP_FILLET",CAMKEY,4,0x2,"Motion Corner Rounding"}, 
	{"CAM_FMILL",CAMKEY,5,0x2,"Flowline Milling"},
	{"CAM_GEO_SHAPE",CAMKEY,6,0x2,"Lathe Shape"}, 
	{"CAM_GEO_SH_ATTRIB",CAMKEY,7,0x2,"Modify Shape Attributes"},
	{"CAM_GEO_SS_EDGE",CAMKEY,8,0x2,"Surf Spline On Surface Edge"}, 
	{"CAM_GEO_SS_IOSF",CAMKEY,9,0x2,"Surf Spline IO Surf & Surf/Plane"},
	{"CAM_CREATE_TEST_CASE",CAMKEY,10,0x2,"Create NCL Test Case"},
	{"CAM_COMMAND",CAMKEY,11,0x2,"Enter Command Mode"},
	{"DUMMY",CAMKEY,12,0x2,"Not Used"}, 
	{"DUMMY",CAMKEY,13,0x2,"Not Used"},
	{"CAM_GEO_SH_MODALS", CAMKEY,14,0x2,"Set Shape Modals"},
	{"CAM_PLAY_CURRENT",CAMKEY,15,0x2,"Current Motion Playback"},
	{"CAM_GEO_CV_OFFCOMP",CAMKEY,16,0x2,"Offset Composite Curve Components"}, 
	{"CAM_SHOW_SOURCE", CAMKEY,17,0x2,"SHOW?SOURCE, SCROLL"},
	{"CAM_EDIT_TOGGLE",CAMKEY,18,0x2,"Toggle Edit Mode"}, 
	{"CAM_AUTONAME_TOGGLE", CAMKEY,19,0x2,"Toggle auto Name"},
	{"CAM_DISPLY_CUTTER",CAMKEY,20,0x2,"Display Cutter"}, 
	{"DUMMY", CAMKEY,21,0x2,"Not Used"},
	{"CAM_ERASE_MOTION",CAMKEY,22,0x2,"Erase Motion"}, 
	{"CAM_STEP_BACKWARD", CAMKEY,23,0x8002,"Step Motion Backward"},
	{"CAM_STEP_FORWARD",CAMKEY,24,0x8002,"Step Motion Forward"}, 
	{"CAM_PLAYBACK",CAMKEY,25,0x2,"Motion Playback Form"},
	{"CAM_PLAYFILE",CAMKEY,26,0x102,"Motion Playback File Form"},
	{"CAM_GEO_PT_XY",CAMKEY,27,0x2,"Point XY Coords"}, 
	{"CAM_GEO_PT_XYZ",CAMKEY,28,0x2,"Point XYZ Coords"},
	{"CAM_GEO_PT_INTOF",CAMKEY,29,0x2,"Point Intof 2 Entities"}, 
	{"CAM_GEO_PT_INTOF3",CAMKEY,30,0x2,"Point Intof 2 Entities"}, 
	{"CAM_GEO_PV_MINUS",CAMKEY,31,0x2,"PtVec Minus PtVec & Vector"}, 
	{"CAM_GEO_VE_MINUS",CAMKEY,32,0x2,"Vector Minus Vector"},
	{"CAM_GEO_PT_ENDPT",CAMKEY,33,0x2,"End Point of Line/Circle"}, 
	{"CAM_GEO_PT_TEND",CAMKEY,34,0x2,"Point Tool End Point"},
	{"CAM_GEO_PT_PN",CAMKEY,35,0x2,"Point from Pattern"}, 
	{"CAM_GEO_PT_CECI",CAMKEY,36,0x2,"Point Center of Circle"},
	{"CAM_GEO_PT_ONSF",CAMKEY,37,0x2,"Point at UV on Surface"}, 
	{"CAM_GEO_WATERLINE",CAMKEY,38,0x2,"Waterline Pocket Roughing"},
	{"CAM_GEO_PT_AACI",CAMKEY,39,0x2,"Point at Angle on Circle"},
	{"CAM_GEO_PT_ONCV",CAMKEY,40,0x2,"Point at U on Curve"}, 
	{"CAM_GEO_PT_DSCV",CAMKEY,41,0x2,"Point at Dist Along Curve"},
	{"CAM_GEO_PT_PTCI",CAMKEY,42,0x2,"Point Thru PT AA Circle"}, 
	{"CAM_GEO_PT_OFFSET",CAMKEY,43,0x2,"Point Offset From Point"},
	{"CAM_GEO_PT_GENPT",CAMKEY,44,0x2,"GENPTS On"},
	{"CAM_GEO_PT_GPTNM",CAMKEY,45,0x2,"GENPTS Nomore"},
	{"CAM_GEO_LN_PTPT",CAMKEY,46,0x2,"Line Thru 2 Points"}, 
	{"CAM_GEO_LN_XY",CAMKEY,47,0x2,"Line Thru 2 XY Location"},
	{"CAM_GEO_LN_XYZ",CAMKEY,48,0x2,"Line Thru 2 XYZ Location"}, 
	{"CAM_GEO_LN_CICI",CAMKEY,49,0x2,"Line Tangent to 2 Circles"},
	{"CAM_GEO_LN_PALN",CAMKEY,50,0x2,"Line Parallel to Line"}, 
	{"CAM_GEO_LN_PL",CAMKEY,51,0x2,"Line From a Plane"},
	{"CAM_GEO_LN_PTPALN",CAMKEY,52,0x2,"Line Thru PT PA to a Line"}, 
	{"CAM_GEO_LN_PTPERPTO",CAMKEY,53,0x2,"Line Thru PT PE to a Line or Curve"},
	{"CAM_GEO_LN_CONNECT",CAMKEY,54,0x2,"Line Connected to last line"}, 
	{"CAM_GEO_LN_PTAALN",CAMKEY,55,0x2,"Line Thru PT AA to a Line"},
	{"NCL_REDEF_SF", CAMKEY, 56, 0x2,"Redef Surface Params"},
	{"CAM_GEO_LN_PTTANTO",CAMKEY,57,0x2,"Line Thru PT TT a Curve or Circle"},
	{"CAM_GEO_LN_PLPL",CAMKEY,58,0x2,"Line Intof Plane/Plane"}, 
	{"CAM_GEO_LN_CIAALN",CAMKEY,59,0x2,"Line Tangent to Circle AA Line"},
	{"CAM_GEO_LN_FWD",CAMKEY,60,0x2,"Line From Tool Forward Dir"}, 
	{"CAM_GEO_LN_XAXIS",CAMKEY,61,0x2,"Line From x_axis"},
	{"CAM_GEO_LN_YAXIS",CAMKEY,62,0x2,"Line From y_axis"}, 
	{"CAM_GEO_LN_OFFSET",CAMKEY,63,0x2,"Line Translated by Vector"},
	{"CAM_GEO_CI_XYR",CAMKEY,64,0x2,"Circle XY Center & Radius"}, 
	{"CAM_GEO_CI_XYZR",CAMKEY,65,0x2,"Circle XYZ Center & Radius"},
	{"CAM_GEO_CI_PTPTVE",CAMKEY,66,0x2,"Circle thru 2 Points w/Tangent Vector"},
	{"CAM_GEO_CI_PTPTPT",CAMKEY,67,0x2,"Circle thru 3 Points"},
	{"CAM_GEO_CV_OFFSET",CAMKEY,68,0x2,"Curve Offset from Curve (along normals)"},
	{"CAM_GEO_CI_TANTO",CAMKEY,69,0x2,"Circle tangent to 2 Entities w/Radius"},
	{"CAM_GEO_CI_LNLNLN",CAMKEY,70,0x2,"Circle tangent to 3 Lines"}, 
	{"CAM_TLAXIS",CAMKEY,71,0x2,"Set Tool Axis Mode"},
	{"CAM_GEO_SP_OFFSET",CAMKEY,72,0x2,"Spline Offset from Spline (along normals)"},
	{"CAM_GEO_CI_CETT",CAMKEY,73,0x2,"Circle Center tangent to Entity"},
	{"CAM_GEO_CI_CELN",CAMKEY,74,0x2,"Circle Center tangent to Line"}, 
	{"CAM_GEO_CI_CECI",CAMKEY,75,0x2,"Circle Center tangent to Circle"},
	{"CAM_GEO_SP_TRANSL",CAMKEY,76,0x2,"Spline Translated by Vector"},
	{"CAM_GEO_CI_CERA",CAMKEY,77,0x2,"Circle Center & Radius"}, 
	{"CAM_GEO_CI_CEPT",CAMKEY,78,0x2,"Circle Center thru Point"}, 
	{"CAM_COMMAND_SRC",CAMKEY,79,0x2,"Set Command Source Format"},
	{"CAM_GEO_CI_PARAM",CAMKEY,80,0x2,"Circle Using 7 Parameters"}, 
	{"CAM_GEO_CI_GEOM",CAMKEY,81,0x2,"Circle Center/Vector/Radius"},
	{"CAM_GEO_CI_TRANSL",CAMKEY,82,0x2,"Circle Translated by Vector"},
	{"CAM_GOTO",CAMKEY,83,0x2,"Goto Tool Location"},
	{"DUMMY",CAMKEY,84,0x2,"No description"},
	{"DUMMY",CAMKEY,85,0x2,"No description "},
	{"DUMMY",CAMKEY,86,0x2,"No description"}, 
	{"DUMMY",CAMKEY,87,0x2,"No description"},
	{"DUMMY",CAMKEY,88,0x2,"No description"},
	{"DUMMY",CAMKEY,89,0x2,"No description"},
	{"DUMMY",CAMKEY,90,0x2,"No description"},
	{"DUMMY",CAMKEY,91,0x2,"No description"},
	{"DUMMY",CAMKEY,92,0x2,"No description"},
	{"CAM_GODLTA",CAMKEY,93,0x2,"Go Delta"},
	{"CAM_PLAYFEED",CAMKEY,94,0x102,"Playback Feedrate Form"}, 
	{"CAM_PLAY_INTERP",CAMKEY,95,0x102,"Playback Interpolation Form"},
	{"CAM_PLAYCLIP",CAMKEY,96,0x2,"Playback Boundary Form"}, 
	{"CAM_PLAY_MODALS",CAMKEY,97,0x2,"Motion Display Modals"},
	{"CAM_SET_MODAL",CAMKEY,98,0x2,"Settings Menu"},
	{"CAM_MACRO_FORM", CAMKEY,99,0x2,"Interactive Macro form design"},
	{"CAM_RUN",CAMKEY,100,0x2,"Run Program Menu"},
	{"CAM_MOTION_CALC",CAMKEY,101,0x2,"Motion Calculation Form"},
	{"CAM_MACRO_CALL",CAMKEY,102,0x2,"Dynamic Macro Call"}, 
	{"CAM_DELETE_LINE",CAMKEY,103,0x2,"Delete Part Program Line"},
	{"CAM_FIND_LINE",CAMKEY,104,0x2,"Find Part program Line"},
	{"CAM_FIND_TOKEN",CAMKEY,105,0x2,"Find Part program Text"},
	{"CAM_INPUT_MODE",CAMKEY,106,0x2,"INPUT"},
	{"CAM_INSERT_MODE",CAMKEY,107,0x2,"INSERT"},
	{"CAM_CONSOL_MODE",CAMKEY,108,0x2,"Consol"}, 
	{"CAM_SKIP_LINE",CAMKEY,109,0x2,"Skip to Program Line"},
	{"CAM_EDIT_LINE",CAMKEY,110,0x2,"Edit Part Program Line"},
	{"CAM_SSRC_CURRENT",CAMKEY,111,0x2,"Show Source From Current Line"},
	{"CAM_SSRC_LINE",CAMKEY,112,0x2,"Show Source From line"},
	{"CAM_SSRC_SCROLL",CAMKEY,113,0x2,"Show Source Scroll"},
	{"CAM_CUTTER_PARMS",CAMKEY,114,0x2,"Cutter Parameter Form"}, 
	{"CAM_CONTOUR",CAMKEY,115,0x2,"Global Contouring Form"},
	{"DUMMY",CAMKEY,116,0x2,"Not used"},
	{"DUMMY",CAMKEY,117,0x2,"Not used"},
	{"DUMMY",CAMKEY,118,0x2,"Not used"}, 
	{"DUMMY",CAMKEY,119,0x2,"Not used"},
	{"DUMMY",CAMKEY,120,0x2,"Not used"}, 
	{"DUMMY",CAMKEY,121,0x2,"Not used"},
	{"DUMMY",CAMKEY,122,0x2,"Not used"},
	{"DUMMY",CAMKEY,123,0x2,"Not used"},
	{"DUMMY",CAMKEY,124,0x2,"Not used"}, 
	{"DUMMY",CAMKEY,125,0x2,"Not used"},
	{"DUMMY",CAMKEY,126,0x2,"Not used"}, 
	{"DUMMY",CAMKEY,127,0x2,"Not used"},
	{"CAM_MULTAX_ON",CAMKEY,128,0x2,"MULTAX/On"}, 
	{"CAM_MULTAX_OFF",CAMKEY,129,0x2,"MULTAX/Off"},
	{"DUMMY",CAMKEY,130,0x2,"Not Used"}, 
	{"DUMMY",CAMKEY,131,0x2,"Not Used"},
	{"CAM_CUT",CAMKEY,132,0x2,"CUT (Pass Points to Clfile)"}, 
	{"CAM_TRACUT",CAMKEY,133,0x2,"Enable TRACUT Matrix"},
	{"CAM_TRACUT_NM",CAMKEY,134,0x2,"Disable TRACUT Matrix"}, 
	{"CAM_DNTCUT",CAMKEY,135,0x2,"DNTCUT (don't output pts)"},
	{"CAM_DNTCUT_NM",CAMKEY,136,0x2,"DNTCUT/NOMORE"}, 
	{"CAM_COPY_SAME",CAMKEY,137,0x2,"Copy Motion No Modification"},
	{"CAM_COPY_MODIFY",CAMKEY,138,0x2,"Copy Motion Matrix"}, 
	{"CAM_COPY_TRANSL",CAMKEY,139,0x2,"Copy Motion Translation"},
	{"CAM_COPY_XYROT",CAMKEY,140,0x2,"Copy Motion XY Rotation"}, 
	{"CAM_COPY_YZROT",CAMKEY,141,0x2,"Copy Motion YZ Rotation"},
	{"CAM_COPY_ZXROT",CAMKEY,142,0x2,"Copy Motion  ZX Rotation"}, 
	{"CAM_INDEX",CAMKEY,143,0x2,"Index Motion Start"},
	{"CAM_INDEX_NM",CAMKEY,144,0x2,"Index Motion Nomore"}, 
	{"CAM_FEDRAT",CAMKEY,145,0x2,"Motion Feedrate"},
	{"DUMMY",CAMKEY,146,0x2,"Not used"}, 
	{"DUMMY",CAMKEY,147,0x2,"Not used"},
	{"DUMMY",CAMKEY,148,0x2,"Not used"}, 
	{"DUMMY",CAMKEY,149,0x2,"Not used "},
	{"CAM_GO",CAMKEY,150,0x2,"Position Tool at Part"}, 
	{"DUMMY",CAMKEY,151,0x2,"Not Used"},
	{"DUMMY",CAMKEY,152,0x2,"Not Used"}, 
	{"DUMMY",CAMKEY,153,0x2,"Not Used"},
	{"DUMMY",CAMKEY,154,0x2,"Not Used"},
	{"DUMMY",CAMKEY,155,0x2,"Not Used"},
	{"DUMMY",CAMKEY,156,0x2,"Not Used"}, 
	{"DUMMY",CAMKEY,157,0x2,"Not Used"},
	{"DUMMY",CAMKEY,158,0x2,"Not Used"}, 
	{"DUMMY",CAMKEY,159,0x2,"Not Used"},
	{"DUMMY",CAMKEY,160,0x2,"Not Used"},
	{"CAM_VOLUMILL_MODALS",CAMKEY,161,0x2,"VoluMill Pocket Modals"},
	{"CAM_POINT_POCKET",CAMKEY,162,0x2,"Simple Pocketing"}, 
	{"CAM_POCKET_MODALS",CAMKEY,163,0x2,"Advanced Pocket Modals"},
	{"CAM_POCKET",CAMKEY,164,0x2,"Advanced Pocketing"}, 
	{"CAM_SCRUB",CAMKEY,165,0x2,"Scrub a Surface"},
	{"CAM_RMILL",CAMKEY,166,0x2,"Regional Mill"}, 
	{"CAM_LATHE_ROUGH",CAMKEY,167,0x2,"Rough Lathe Shape"},
	{"CAM_LATHE_FINISH",CAMKEY,168,0x2,"Finish Lathe Shape"},
	{"CAM_REMOVE_GEO",CAMKEY,169,0x2,"Remove geometry"}, 
	{"CAM_REDEF_FILLET",CAMKEY,170,0x2,"Trim Circle to 2 Lines"},
	{"CAM_REDEF_CLOSE",CAMKEY,171,0x2,"Define Geo as Opened/closed"}, 
	{"CAM_REVERSE_GEO",CAMKEY,172,0x2,"Reverse Direction of geo"},
	{"CAM_COPY_SCALE",CAMKEY,173,0x2,"Copy Geo Thru Scale Matrix"}, 
	{"CAM_COPY_PTPT",CAMKEY,174,0x2,"Copy geo Point to Point"},
	{"CAM_COPY_VECTOR",CAMKEY,175,0x2,"Copy Geo Using Vector"}, 
	{"CAM_COPY_ROTATE",CAMKEY,176,0x2,"Copy geo Using Rotation"},
	{"CAM_COPY_MIRROR",CAMKEY,177,0x2,"Copy geo Using Mirror MX"}, 
	{"CAM_COPY_MATRIX",CAMKEY,178,0x2,"Copy geo Using Matrix"},
	{"CAM_MOVE_SCALE",CAMKEY,179,0x2,"Move Geo Thru Scale Matrix"}, 
	{"CAM_MOVE_PTPT",CAMKEY,180,0x2,"Move Geo Point to Point"},
	{"CAM_MOVE_VECTOR",CAMKEY,181,0x2,"Move Geo Using Vector"},
	{"CAM_MOVE_ROTATE",CAMKEY,182,0x2,"Move Geo Using Rotation"},
	{"CAM_MOVE_MIRROR",CAMKEY,183,0x2,"Move Geo Using Mirror MX"},
	{"CAM_MOVE_MATRIX",CAMKEY,184,0x2,"Move Geo Using Matrix"},
	{"CAM_GEO_PL_IJKD",CAMKEY,185,0x2,"Plane IJK Vector & distance"},
	{"CAM_GEO_PL_PTPTPT",CAMKEY,186,0x2,"Plane Thru 3 Points"},
	{"CAM_GEO_PL_PTPAPL",CAMKEY,187,0x2,"Plane Thru PT PA to a Plane"}, 
	{"CAM_GEO_PL_PAPL",CAMKEY,188,0x2,"Plane Parallel to a Plane"},
	{"CAM_GEO_PL_PTPEVE",CAMKEY,189,0x2,"Plane Thru PT PE to Vector"}, 
	{"CAM_GEO_PL_PTPTPE",CAMKEY,190,0x2,"Plane Thru 2 PTs PE to PL"},
	{"CAM_GEO_PL_PTPEPL",CAMKEY,191,0x2,"Plane Thru PT PE to 2 PLs"}, 
	{"CAM_GEO_PL_LNPEPL",CAMKEY,192,0x2,"Plane Thru LN PE to Plane"},
	{"CAM_GEO_PL_PNTVEC",CAMKEY,193,0x2,"Plane Perpto Point Vector"}, 
	{"CAM_GEO_CV_PT",CAMKEY,194,0x2,"Curve by multiple PTS/PVS"},
	{"CAM_GEO_CV_PTVE",CAMKEY,195,0x2,"Curve by multiple PTS & VES"}, 
	{"CAM_GEO_CV_PTPT",CAMKEY,196,0x2,"Curve Point Thru Point"},
	{"CAM_GEO_SP_IOSF",CAMKEY,197,0x2,"Spline IO Surf & Surf/Plane"},
	{"CAM_GEO_CV_FIT_PTS",CAMKEY,198,0x2,"Curve Fit Point Thru Point"},
	{"CAM_GEO_CV_FIT_PTPT",CAMKEY,199,0x2,"Curve Fit multiple PTS/PVS"},
	{"CAM_GEO_CV_EDGE",CAMKEY,200,0x2,"Curve as Surface Edge"},
	{"CAM_GEO_CV_IOSF",CAMKEY,201,0x2,"Curve IO Surf & Surf/Plane"}, 
	{"CAM_GEO_CV_TRANSL",CAMKEY,202,0x2,"Curve Translated by Vector"},
	{"CAM_GEO_CV_CONIC",CAMKEY,203,0x2,"Curve Defined as Conic"},
	{"CAM_GEO_CV_COMPOSIT",CAMKEY,204,0x2,"Composite Curve"},
	{"CAM_GEO_CV_FIT_PTVE",CAMKEY,205,0x2,"Curve Fit multiple PTS & VES"},
	{"CAM_GEO_SP_PT",CAMKEY,206,0x2,"Spline by Multi PTS/PVS"},
	{"CAM_GEO_SP_PTVE",CAMKEY,207,0x2,"Spline by Multi PTS & VES"}, 
	{"CAM_GEO_SP_PTPT",CAMKEY,208,0x2,"Spline Point Thru Point"},
	{"CAM_GEO_SP_EDGE",CAMKEY,209,0x2,"Spline as (Base) Surface Edge"}, 
	{"CAM_GEO_SP_FIT_PTS",CAMKEY,210,0x2,"Spline Fit Point Thru Point"},
	{"CAM_GEO_SP_FIT_PTPT",CAMKEY,211,0x2,"Spline Fit Multi PTS/PVS"}, 
	{"CAM_GEO_SP_FIT_PTVE",CAMKEY,212,0x2,"Spline Fit Multi PTS & VES"},
	{"CAM_GEO_VE_IJK",CAMKEY,213,0x2,"Vector IJK Component"},
	{"CAM_GEO_VE_FWD",CAMKEY,214,0x2,"Vector Tool Forward Direc"},
	{"CAM_GEO_VE_TA",CAMKEY,215,0x2,"Vector Tool Axis"}, 
	{"CAM_GEO_VE_PTPT",CAMKEY,216,0x2,"Vector Thru 2 Points"},
	{"CAM_GEO_VE_PV",CAMKEY,217,0x2,"Vector From Point Vector"},
	{"CAM_GEO_VE_PEPL",CAMKEY,218,0x2,"Vector Perpto a Plane"},
	{"CAM_GEO_VE_UNIT",CAMKEY,219,0x2,"Vector Unit len of Vector"},
	{"CAM_GEO_VE_PLUS",CAMKEY,220,0x2,"Vector Plus 2 Vectors"},
	{"CAM_GEO_VE_CROSS",CAMKEY,221,0x2,"Vector Cross of 2 Vectors"},
	{"CAM_GEO_VE_TIMES",CAMKEY,222,0x2,"Vector Times 2 Vectors"},
	{"CAM_GEO_VE_IOPL",CAMKEY,223,0x2,"Vector Intof 2 Planes"},
	{"CAM_GEO_VE_PTSF",CAMKEY,224,0x2,"Vector Thru a Point PE Surf"},
	{"CAM_GEO_VE_TTCV",CAMKEY,225,0x2,"Vector Tanto a Curve"},
	{"CAM_GEO_SF_NET_THRU",CAMKEY,226,0x2,"Net Surface SF Thru SF"},
	{"CAM_GEO_SF_OUT",CAMKEY,227,0x2,"Extract Base Surf from Trim Surf"}, 
	{"CAM_GEO_SF_RULED",CAMKEY,228,0x2,"Surface Thru 2 Entities"},
	{"CAM_GEO_SF_CURVES",CAMKEY,229,0x2,"Surface Thru Entities w/Slopes"},
	{"CAM_GEO_SF_CURVES0",CAMKEY,230,0x2,"Surface Thru Multi Entities"},
	{"CAM_GEO_SF_FIT",CAMKEY,231,0x2,"Surface Fit Thru Entities"},
	{"CAM_GEO_SF_FIT_THRU",CAMKEY,232,0x2,"Surface Fit Ent Thru Ent"},
	{"CAM_GEO_SF_OFFSET",CAMKEY,233,0x2,"Surface Offset from Trim Surf"}, 
	{"CAM_GEO_SF_PLPLRA",CAMKEY,234,0x2,"Fillet Surface Tanto 2 PLS"},
	{"CAM_GEO_SF_FILLET",CAMKEY,235,0x2,"Variable Fillet Surface"},
	{"CAM_GEO_SF_MESH",CAMKEY,236,0x2,"Mesh Surface"},
	{"CAM_GEO_SF_QUILT",CAMKEY,237,0x2,"Quilt Surface"},
	{"CAM_GEO_SF_NET",CAMKEY,238,0x2,"Net Surface"},
	{"CAM_GEO_SF_MODALS",CAMKEY,239,0x2,"Set Surface Modals"}, 
	{"CAM_GEO_SF_ATTRIB",CAMKEY,240,0x2,"Modify Surface Attributes"},
	{"CAM_GEO_NF_RULED",CAMKEY,241,0x2,"N-surf Thru 2 Entities"},
	{"CAM_GEO_NF_CURVES",CAMKEY,242,0x2,"N-Surf Thru Entities w/Slopes"},
	{"CAM_GEO_NF_CURVES0",CAMKEY,243,0x2,"N-surf Thru Multi Entities"}, 
	{"CAM_GEO_NF_FIT",CAMKEY,244,0x2,"N-Surf Fit Thru Entities"},
	{"CAM_GEO_NF_FIT_THRU",CAMKEY,245,0x2,"N-Surf Fit Thru Entities"}, 
	{"CAM_GEO_NF_4CV",CAMKEY,246,0x2,"N-Surf Using 4 Boundary CVS"},
	{"CAM_GEO_NF_REVOLVE",CAMKEY,247,0x2,"N-Surf of Revolution"},
	{"CAM_GEO_PN_PTPTVE",CAMKEY,248,0x2,"Pattern Using 2 PTs and VE"},
	{"CAM_GEO_PN_PTVEIN",CAMKEY,249,0x2,"Pattern at PT Incr Along VE"}, 
	{"CAM_GEO_PN_CIRC",CAMKEY,250,0x2,"Circular Pattern"},
	{"CAM_GEO_PN_CIRCIN",CAMKEY,251,0x2,"Circular Incr Pattern"}, 
	{"CAM_GEO_PN_PNVE",CAMKEY,252,0x2,"Pattern PA Pattern Along VE"},
	{"CAM_GEO_PN_PNVEIN",CAMKEY,253,0x2,"Pattern at PT Incr Along VE"}, 
	{"CAM_GEO_PN_PTPN",CAMKEY,254,0x2,"Random Pattern"},
	{"CAM_GEO_MX_PTVEVE",CAMKEY,255,0x2,"Matrix Using Point VE VE"}, 
	{"CAM_GEO_MX_INVERSE",CAMKEY,256,0x2,"Matrix Inverse Matrix"},
	{"CAM_GEO_MX_MXMX",CAMKEY,257,0x2,"Matrix Times  Matrix"}, 
	{"CAM_GEO_MX_MIRROR",CAMKEY,258,0x2,"Mirror Matrix"},
	{"CAM_GEO_MX_SCALE",CAMKEY,259,0x2,"Scale Matrix"}, 
	{"CAM_GEO_MX_ROTATE",CAMKEY,260,0x2,"Rotation  Matrix"},
	{"CAM_GEO_MX_TRANSL",CAMKEY,261,0x2,"Translation Matrix"}, 
	{"CAM_GEO_MX_PARAMS",CAMKEY,262,0x2,"Matrix  Using 12 Parameters"},
	{"CAM_GEO_SH_PPWORDS",CAMKEY,263,0x2,"Set Shape Post Words"},
	{"CAM_STAT_GEO",CAMKEY,264,0x2,"Show geometry Canon Data"}, 
	{"CAM_STAT_CUTTER",CAMKEY,265,0x2,"Show Cutter Parameters"},
	{"CAM_STAT_FILES",CAMKEY,266,0x2,"Show Current Files"},
	{"CAM_STAT_THICK",CAMKEY,267,0x2,"Show Current Thick"},
	{"CAM_STAT_TOLER",CAMKEY,268,0x2,"Show Current Tolerance"}, 
	{"CAM_STAT_TOOL",CAMKEY,269,0x2,"Show Tool Position"},
	{"CAM_STAT_MODALS",CAMKEY,270,0x2,"Show CAM modals"}, 
	{"CAM_LOAD_PP",CAMKEY,271,0x2,"Load Part Program File"},
	{"CAM_SAVE_PP",CAMKEY,272,0x2,"Save Part Program File"}, 
	{"CAM_EDIT_PP",CAMKEY,273,0x2,"Edit Part program File"},
	{"DUMMY",CAMKEY,274,0x2,"Not used"},
	{"CAM_GEO_PV_TTPE",CAMKEY,275,0x2,"PtVec Tanto or Perpto Geo"},
	{"CAM_GEO_SF_REVOLVE",CAMKEY,276,0x2,"Surface of Revolution"}, 
	{"CAM_REVERS_ON",CAMKEY,277,0x2,"Start Reversal of Clfile"},
	{"CAM_REVERS_OFF",CAMKEY,278,0x2,"End Reversal of Clfile"},
	{"CAM_GET_ALL",CAMKEY,279,0x2,"Get All Geometry"},
	{"CAM_GET_GEO",CAMKEY,280,0x2,"Get Geometry"},
	{"CAM_GET_GEO_RENAME",CAMKEY,281,0x2,"Get and Rename Geo"},
	{"CAM_GET_GEO_THRU",CAMKEY,282,0x2,"Get Thru Geo"},
	{"CAM_GET_GEO_THRU_RE",CAMKEY,283,0x2,"Get and Rename Thru Geo"},
	{"CAM_GET_LAYER",CAMKEY,284,0x2,"Get By Layer"},
	{"CAM_GET_TYPE",CAMKEY,285,0x2,"Get Geo Type"},
	{"CAM_PUT_ALL",CAMKEY,286,0x2,"Put All Geometry"},
	{"CAM_PUT_GEO",CAMKEY,287,0x2,"Put Geometry"},
	{"CAM_PUT_GEO_THRU",CAMKEY,288,0x2,"Put Thru Geo"},
	{"CAM_CREATE_CL",CAMKEY,289,0x2,"Create Clfile"}, 
	{"CAM_CREATE_AS",CAMKEY,290,0x2,"Create APT Source File"},
	{"CAM_EDIT_CL",CAMKEY,291,0x2,"Edit Active Clfile"}, 
	{"CAM_ERASE_CL",CAMKEY,292,0x2,"Erase Active Clfile"},
	{"CAM_SEQUNC_LIST",CAMKEY,293,0x2,"List Machining Sequence"}, 
	{"CAM_SEQUNC_START",CAMKEY,294,0x2,"Start Machining Sequence"},
	{"CAM_SEQUNC_END",CAMKEY,295,0x2,"End Machining Sequence"}, 
	{"CAM_SEQUNC_ERASE",CAMKEY,296,0x2,"Erase Machining Sequence"},
	{"CAM_GEO_PV_XYIJK",CAMKEY,297,0x2,"PtVec XY Coords IJK Vector"},
	{"CAM_GEO_PV_XYZIJK",CAMKEY,298,0x2,"PtVec XYZ Coords IJK Vector"},
	{"CAM_GEO_PV_PTPT",CAMKEY,299,0x2,"PtVec Thru 2 Points"},
	{"CAM_GEO_PV_PTVE",CAMKEY,300,0x2,"PtVec at a Point w/Vector"},
	{"CAM_GEO_PV_LN",CAMKEY,301,0x2,"PtVec From a Line"},
	{"CAM_GEO_PV_TETA",CAMKEY,302,0x2,"PtVec Tool End & Tlaxis"},
	{"CAM_GEO_PV_TEFWD",CAMKEY,303,0x2,"PtVec Tool End & FWD Vector"}, 
	{"CAM_GEO_PV_CECI",CAMKEY,304,0x2,"PtVec CE of Circle w/Axis"},
	{"CAM_GEO_PV_PLPLPL",CAMKEY,305,0x2,"PtVec Intof 3 Planes"},
	{"CAM_GEO_PV_DSCV",CAMKEY,306,0x2,"PtVec at Dist Along Curve"},
	{"CAM_GEO_PV_PLUS",CAMKEY,307,0x2,"PtVec Plus PtVec & Vector"}, 
	{"CAM_GEO_PV_CROSS",CAMKEY,308,0x2,"PtVec Cross of PV & Vec"},
	{"CAM_GEO_PV_UNIT",CAMKEY,309,0x2,"PtVec Unit Len of PtVec"}, 
	{"CAM_GEO_PV_PEPL",CAMKEY,310,0x2,"PtVec Perpto a Plane"},
	{"CAM_PUT_GEO_TYPE",CAMKEY,311,0x2,"Put Geo Type"}, 
	{"CAM_GEO_PV_TIMES",CAMKEY,312,0x2,"PtVec Times PtVec & Vector"},
	{"CAM_GEO_PV_OFFSET",CAMKEY,313,0x2,"PtVec Offset From PtVec"},
	{"CAM_PUT_LAYER",CAMKEY,314,0x2,"Put By Layer"},
	{"CAM_GEO_PV_PN",CAMKEY,315,0x2,"PtVec From a Pattern"}, 
	{"CAM_GEO_PV_GENPT",CAMKEY,316,0x2,"GENPTS On"},
	{"DUMMY",CAMKEY,317,0x2,"Not Used"}, 
	{"DUMMY",CAMKEY,318,0x2,"Not Used"},
	{"CAM_LOOPST",CAMKEY,319,0x2,"LOOPST Statement"},
	{"CAM_DOLOOP",CAMKEY,320,0x2,"Start DO Loop"},
	{"CAM_STATEMENT",CAMKEY,321,0x2,"Single NCL Command"}, 
	{"CAM_IF",CAMKEY,322,0x2,"IF Statement"},
	{"CAM_JUMPTO",CAMKEY,323,0x2,"JUMPTO Statement"},
	{"CAM_UNDO",CAMKEY,324,0x2,"UNDO Statement"},
	{"CAM_LOOPND",CAMKEY,325,0x2,"LOOPND Statement"}, 
	{"CAM_TERMAC",CAMKEY,326,0x2,"TERMAC"},
	{"CAM_FINI",CAMKEY,327,0x2,"FINI"},
	{"CAM_MODSYS",CAMKEY,328,0x2,"Enable MODSYS Matrix"},
	{"CAM_MODSYS_NM",CAMKEY,329,0x2,"Disable MODSYS Matrix"},
	{"CAM_REFSYS",CAMKEY,330,0x2,"Enable REFSYS"},
	{"CAM_REFSYS_NM",CAMKEY,331,0x2,"Disable REFSYS"},
	{"CAM_ZSURF",CAMKEY,332,0x2,"ZSURF Statement"},
	{"CAM_FUNC_CAN",CAMKEY,333,0x2,"CAN Function"}, 
	{"CAM_GEO_PV_REVSF",CAMKEY,334,0x2,"PtVec along axis of revsf"}, 
	{"CAM_GEO_SP_REVSF",CAMKEY,335,0x2,"Generating Curve of revsf"}, 
	{"CAM_GEO_SS_REVSF",CAMKEY,336,0x2,"Sspline along generatrix of revsf"}, 
	{"CAM_SYM_TABLE",CAMKEY,337,0x2,"Display Symbol List Form"},
	{"CAM_GET_DATA",CAMKEY,338,0x2,"Get Variables from Secondary Unibase"},
	{"CAM_PUT_DATA",CAMKEY,339,0x2,"Put Variables to Secondary Unibase"}, 

	{"CAM_GEO_PV_ONCV",CAMKEY,340,0x2,"PtVec at U on Curve"},
	{"CAM_GEO_PV_ONSF",CAMKEY,341,0x2,"PtVec at UV on Surface"},
	{"CAM_UBFN_INVIS_GEO",CAMKEY,342,0x16,"Invisible Geometry from second unibase"}, 
	{"CAM_UBFN_INVIS_ALL",CAMKEY,343,0x16,"Invisible All displayed from second unibase"},
	{"CAM_UBFN_VIS_GEO",CAMKEY,344,0x16,"Visible Entities from second unibase"}, 
	{"CAM_UBFN_VIS_ALL",CAMKEY,345,0x16,"Visible All Entities from second unibase"},

	{"CAM_GEO_TRIM_REMALL",CAMKEY,346,0x2,"Remove All Inner Boundaries"},
	{"CAM_FUNC_NRESERV",CAMKEY,347,0x2,"NUM(Reserved) Function"},
	{"CAM_FUNC_NPATERN",CAMKEY,348,0x2,"NUM(Patern) Function"},
	{"CAM_GEO_SP_OUT",CAMKEY,349,0x2,"Extract Trim Surf Boundary Spline"},
	{"CAM_GEO_SS_OUT",CAMKEY,350,0x2,"Extract Trim Surf Boundary Curve"},
	{"CAM_GEO_SS_EDGE_OUT",CAMKEY,351,0x2,"Extract Trimmed Edge Spline"},
	{"CAM_GEO_SP_EDGE_OUT",CAMKEY,352,0x2,"Extract Trimmed Edge Curve"},
	{"CAM_GEO_PT_PROJECT", CAMKEY, 353, 0x2,"Project Point onto Surface"},
	{"CAM_GEO_PV_PROJECT", CAMKEY, 354, 0x2,"Project PointVector on Surface"},
	{"CAM_GEO_PN_PROJECT", CAMKEY, 355, 0x2,"Project Pattern onto Surface"},
	{"CAM_GEO_SF_TRIM", CAMKEY, 356, 0x2,"Trim a Surface"},
	{"CAM_GEO_SF_REDEF", CAMKEY, 357, 0x2,"Redef a Surface"},
	{"CAM_GEO_SP_PROJECT", CAMKEY, 358, 0x2,"Project onto Surface"},
	{"CAM_GEO_SS_PROJECT", CAMKEY, 359, 0x2,"Project onto Surface"},
	{"CAM_GEO_PL_PTVEVE",CAMKEY,360,0x2,"Plane Thru PT PA to 2 Vectors"}, 
	{"CAM_UBFN_OPEN",CAMKEY,361,0x2,"Open Secondary Unibase"},
	{"CAM_UBFN_CLOSE",CAMKEY,362,0x2,"Close Secondary Unibase"},
	{"CAM_GEO_CI_OFFSET",CAMKEY,363,0x2,"Circle Offset from Circle"},
	{"CAM_GEO_COMPCV_OUT",CAMKEY,364,0x2,"Extract a Composite Component"},
	{"CAM_GEO_SFS_CONTOUR", CAMKEY, 365, 0x2,"Contour around Surfaces"},
	{"CAM_GEO_SFS_IO", CAMKEY, 366, 0x2,"Intof Z-level Plane with Surfaces"},
	{"CAM_GEO_TRIM_REMOVE", CAMKEY, 367, 0x2,"Remove Trimmed Surface Boundaries"},
	{"CAM_PROFILE",CAMKEY,368,0x2,"Profile Machining Form"},
	{"CAM_SCALARS",CAMKEY,369,0x2,"Display Scalar List Form"},
	{"CAM_SCALAR_DEFINE",CAMKEY,370,0x2,"Define a Scalar"},
	{"CAM_GET_ALL_RENAME",CAMKEY,371,0x2,"Get and Rename All Geometry"},
	{"CAM_GEO_PL_FIT",CAMKEY,372,0x2,"Optimal plane cv/sf"},
	{"CAM_GEO_PV_FIT",CAMKEY,373,0x2,"PtVec center cv/sf"}, 
	{"CAM_GEO_PT_FIT",CAMKEY,374,0x2,"Pt center cv/sf"},
	{"CAM_GEO_ANOTE",CAMKEY,375,0x2,"Create CAM Annotation"},
	{"CAM_ANOTE_ATTRIBS",CAMKEY,376,0x2,"Set CAM Annotation Attributes"},
	{"CAM_ANOTE_MODIFY",CAMKEY,377,0x2,"Modify CAM Annotation Attributes"},
	{"CAM_ANOTE_ENGRAVE",CAMKEY,378,0x2,"Engrave CAM Annotation"},
	{"CAM_DECOMP_SYM",CAMKEY,379,0x2,"CAM Decompose Symbol"},
	{"CAM_SOLID_BXPT",CAMKEY,380,0x2,"Solid Box From 2 PTS"}, 
	{"CAM_SOLID_BXLEN",CAMKEY,381,0x2,"Solid Box From CEN & LEN"},
	{"CAM_SOLID_CONPT",CAMKEY,382,0x2,"Solid Cone From 2 PTS"}, 
	{"CAM_SOLID_CONCE",CAMKEY,383,0x2,"Solid Cone From Center"}, 
	{"CAM_SOLID_CYLCI",CAMKEY,384,0x2,"Solid Cyl From Circle"}, 
	{"CAM_SOLID_CYLPT",CAMKEY,385,0x2,"Solid Cyl From 2 PTS"},
	{"CAM_SOLID_CYLCE",CAMKEY,386,0x2,"Solid Cyl From Center"},
	{"CAM_SOLID_SWEEP",CAMKEY,387,0x2,"Solid Profile Sweep"},
	{"CAM_SOLID_CONTOUR",CAMKEY,388,0x2,"Solid Contour"},
	{"CAM_SOLID_REVOLVE",CAMKEY,389,0x2, "Solid Revolve"}, 
	{"CAM_SOLID_SPHCI",CAMKEY,390,0x2,"Solid Sphere From Circle"}, 
	{"CAM_SOLID_SPHCE",CAMKEY,391,0x2,"Solid Sphere From Center"}, 
	{"CAM_SOLID_TORCI",CAMKEY,392,0x2,"Solid Torus From Circle"}, 
	{"CAM_SOLID_TORRA",CAMKEY,393,0x2,"Solid Torus From Circle/Radius"}, 
	{"CAM_SOLID_TORCE",CAMKEY,394,0x2,"Solid Torus From Center"}, 
	{"CAM_SOLID_LOAD",CAMKEY,395,0x2,"Load Solid Prims"}, 
	{"CAM_SOLID_SAVE",CAMKEY,396,0x2,"Save Solid Prims"}, 
	{"CAM_SOLID_BOUND",CAMKEY,397,0x2,"Solid Bounding Box"}, 
	{"CAM_SOLID_STL",CAMKEY,398,0x2,"Load Solid STL File"}, 
	{"CAM_SAVE_STL",CAMKEY,399,0x2,"Save STL File"}, 
	{"CAM_MOTION_DATA",CAMKEY,400,0x2,"Motion Data"}, 
	{"CAM_GEO_SS_OFFSET",CAMKEY,401,0x2,"Create Offset Surface-Spline)"},
	{"CAM_GEO_SS_EDGES_OUT",CAMKEY,402,0x2,"Extract Trimmed Edges Spline"},
	{"CAM_GEO_SP_EDGES_OUT",CAMKEY,403,0x2,"Extract Trimmed Edges Curve"},
	{"CAM_PMILL",CAMKEY,404,0x2,"Port Surface Machining"},
	{"CAM_SMILL",CAMKEY,405,0x2,"Mutilple Surface Machining"},
	{"CAM_GEO_DATA",CAMKEY,406,0x2,"DATA Statement Definition"},
	{"CAM_GEO_MX_COORDSYS",CAMKEY,407,0x2,"Matrix Using 3 Pairs of Points"}, 
	{"CAM_STEP_BEGIN",CAMKEY,408,0x2,"Step Motion to Beginning"},
	{"CAM_STEP_END",CAMKEY,409,0x2,"Step Motion to End"},
	{"CAM_STEP_PICK",CAMKEY,410,0x2,"Step Motion to Pick"},
	{"CAM_VOLUMILL",CAMKEY,411,0x2,"VoluMill Pocketing"},
	{"CAM_GEO_DATA_FILE",CAMKEY,412,0x2,"DATA Statement Definition From File"},
	{"CAM_DATA_FORM",CAMKEY,413,0x2,"DATA Selection Form"},
	{"CAM_RESET_CALL",CAMKEY,414,0x2,"Reset Macro/Loop Calls"},
	{"CAM_SOLID_COMPOS",CAMKEY,415,0x2,"Define Composite Solid"}, 
	{"CAM_DECOMP_ENTITY",CAMKEY,416,0x2,"Extract Solid/Surface Component"}, 
	{"CAM_GEO_SS_COMPOS",CAMKEY,417,0x2,"Composite Curve from Surface splines"}, 

	{"CAD_RENAME_GEO",CADKEY,0,0x4,"Rename Geometry"},
	{"DUMMY",CADKEY,1,0x4,"No description"},
	{"DUMMY",CADKEY,2,0x4,"No description"}, 
	{"DUMMY",CADKEY,3,0x4,"No description"},
	{"CAD_PLACE_SYM",CADKEY,4,0x14,"Place Symbol"},
	{"CAD_DECOMP_SYM",CADKEY,5,0x14,"Decompose Symbol"},
	{"CAD_SYM_ATTRIB",CADKEY,6,0x14,"Set Symbol Library"}, 
	{"CAD_SYM_TEXTATT",CADKEY,7,0x14,"Set Symbol Text Attribs"},
	{"CAD_SYM_TEXTVIS",CADKEY,8,0x14,"Set Symbol Text Visibility"}, 
	{"CAD_SYM_CREMASTER",CADKEY,9,0x14,"Create Symbol"},
	{"CAD_SYM_DELMASTER",CADKEY,10,0x14,"Delete Lbrary Symbol"}, 
	{"CAD_SYM_RENMASTER",CADKEY,11,0x14,"Rename Library Symbol"},
	{"CAD_SYM_SAVMASTER",CADKEY,12,0x14,"Archive Symbol"}, 
	{"DUMMY",CADKEY,13,0x14,"No description"},
	{"DUMMY",CADKEY,14,0x14,"No description"},
	{"DUMMY",CADKEY,15,0x14,"No description"},
	{"CAD_SYM_LOADMASTER",CADKEY,16,0x14,"Load Library Symbol"}, 
	{"CAD_SYM_LOADLIB",CADKEY,17,0x14,"Load Symbol Library"},
	{"CAD_SYM_UNLOADMAS",CADKEY,18,0x14,"Remove Symbol"},
	{"CAD_SYM_RENAME",CADKEY,19,0x14,"Rename Symbol"},
	{"CAD_SYM_CRELIB",CADKEY,20,0x14,"Create Symbol Library"},
	{"CAD_SYM_DELLIB",CADKEY,21,0x14,"Delete Symbol Library"},
	{"CAD_SYM_RENLIB",CADKEY,22,0x14,"Rename Symbol Library"},
	{"CAD_CREATE_FEATURE",CADKEY,23,0x14,"Create Feature"}, 
	{"CAD_DELETE_FEATURE",CADKEY,24,0x14,"Delete Feature"},
	{"CAD_2D_ANALYSIS",CADKEY,25,0x14,"2D Geometry Analysis"},
	{"CAD_2D_MODALS",CADKEY,26,0x14,"2D Geometry Analysis Modals"},
	{"CAD_GEO_PT_XY",CADKEY,27,0x14,"Point XY Coords"},
	{"CAD_GEO_PT_DELTA",CADKEY,28,0x14,"Point Offset From Point"},
	{"CAD_GEO_PT_IO",CADKEY,29,0x14,"Point Intof 2 Entities"}, 
	{"CAD_GEO_PT_ONCV",CADKEY,30,0x14,"Point at U-value on Curve"},
	{"CAD_GEO_PT_ONENT",CADKEY,31,0x14,"Point on Geometry Entity "}, 
	{"CAD_GEO_PT_ONSF",CADKEY,32,0x14,"Point on Surface"},
	{"CAD_GEO_PN_LINEAR",CADKEY,33,0x14,"Linear Pattern of Points"}, 
	{"CAD_GEO_PN_CIRC",CADKEY,34,0x14,"Circular Pattern of Points"},
	{"CAD_GEO_LN_PTPT",CADKEY,35,0x14,"Line Thru 2 PTS"},
	{"CAD_GEO_LN_CON",CADKEY,36,0x14,"Series of Connected Lines"},
	{"CAD_GEO_LN_PTTA",CADKEY,37,0x14,"Line Thru PT Tanto Entity"}, 
	{"CAD_GEO_LN_TANTO",CADKEY,38,0x14,"Line Tanto 2 Entities"},
	{"CAD_GEO_LN_PTTACV",CADKEY,39,0x14,"Line Thru PT Tanto Curve"},
	{"CAD_GEO_LN_PALN",CADKEY,40,0x14,"Line parallel to a Line"},
	{"CAD_GEO_LN_PTPALN",CADKEY,41,0x14,"Line Thru PT PA to a Line"},
	{"CAD_GEO_LN_PTPE",CADKEY,42,0x14,"Line Thru PT PE to Entiry"},
	{"CAD_GEO_LN_PTPECV",CADKEY,43,0x14,"Line Thru PT PE to a Curve"},
	{"CAD_GEO_LN_ATANGL",CADKEY,44,0x14,"Line Thru PT AA to a Line"},
	{"CAD_GEO_LN_AXIS",CADKEY,45,0x14,"Line Parallel to Vector"}, 
	{"CAD_GEO_LN_CHAMF",CADKEY,46,0x14,"Line Defined as a Chamfer"},
	{"CAD_GEO_LN_MCHAMF",CADKEY,47,0x14,"Line Defined as Multi Chamfers"},
	{"CAD_GEO_ARC_PTPTPT",CADKEY,48,0x14,"Arc Thru 3 Points"},
	{"CAD_GEO_ARC_CERA",CADKEY,49,0x14,"Arc Center & radius"}, 
	{"CAD_GEO_ARC_CEPTPT",CADKEY,50,0x14,"Arc Center & 2 PTS"},
	{"CAD_GEO_ARC_TTRA",CADKEY,51,0x14,"Arc TT 2 Entities & Radius"}, 
	{"CAD_GEO_ARC_TANTO",CADKEY,52,0x14,"Arc Tangent to 3 Lines"},
	{"CAD_GEO_ARC_FILLET",CADKEY,53,0x14,"Single Arc Fillet"},
	{"CAD_GEO_ARC_MFILLET",CADKEY,54,0x16,"Multi Arc Fillet"},
	{"CAD_GEO_CI_PTPTPT",CADKEY,55,0x14,"Circle Thru 3 PTS"},
	{"CAD_GEO_CI_PTPTDI",CADKEY,56,0x14,"Circle Thru 2 Dimension PTS"},
	{"CAD_GEO_CI_CERA",CADKEY,57,0x14,"Circle Center & Radius"}, 
	{"CAD_GEO_CI_CEPT",CADKEY,58,0x14,"Circle Center & Point On CI"},
	{"CAD_GEO_CI_CETT",CADKEY,59,0x14,"Circle Center Tanto Entity"},
	{"CAD_GEO_CI_TTRA",CADKEY,60,0x14,"Arc TT 2 Entities & Radius"},
	{"CAD_GEO_CI_TANTO",CADKEY,61,0x14,"Circle Tangent to 3 Lines"}, 
	{"CAD_GEO_CI_NCIRC",CADKEY,62,0x14,"Multiple Circles w/Radius"},
	{"CAD_GEO_CV_INTERP",CADKEY,63,0x14,"Curve From Multi Points"}, 
	{"CAD_GEO_CV_FIT",CADKEY,64,0x14,"Curve Fit From Multi Points"},
	{"CAD_GEO_CV_ELPCEN",CADKEY,65,0x14,"Ellipse By Center and axes"},
	{"CAD_GEO_CV_ELPLIN",CADKEY,66,0x14,"Ellipse Tanto 2 Lines"},
	{"CAD_GEO_CV_PBFOCUS",CADKEY,67,0x14,"Parabola by Vertex & Focus"},
	{"CAD_GEO_CV_PBTANTO",CADKEY,68,0x14,"Parabola by EndPT & Tan Vec"},
	{"CAD_GEO_CV_HYPERB",CADKEY,69,0x14,"Hyperbola"},
	{"CAD_GEO_CV_CONTAN",CADKEY,70,0x14,"Conic Thru Multi PTS/Tans"},
	{"CAD_GEO_CV_ABCDEF",CADKEY,71,0x14,"Conic Using Coefficients"},
	{"CAD_GEO_CV_PB4PTS",CADKEY,72,0x14,"Parabola by 4 points"},
	{"CAD_GEO_CM_MERGE",CADKEY,73,0x14,"Composite Curve Merge"}, 
	{"CAD_GEO_CM_INTERP",CADKEY,74,0x14,"Composite Curve Interpolate"},
	{"CAD_GEO_CM_SPLIT",CADKEY,75,0x14,"Split Composite Curve"}, 
	{"CAD_GEO_CM_DISOLV",CADKEY,76,0x14,"Dissolve Composite Curve"},
	{"CAD_GEO_EXTR_LINEAR",CADKEY,77,0x4,"Linear Extrusion"},
	{"CAD_GEO_EXTR_CIRC",CADKEY,78,0x4,"Rotational Extrusion"},
	{"CAD_GEO_EXTR_PROJECT",CADKEY,79,0x4,"Planar Projection"},
	{"CAD_GEO_SF_PLANE",CADKEY,80,0x4,"Planar Surface"},
	{"CAD_GEO_SF_CYL",CADKEY,81,0x4,"Cylindrical Surface"},
	{"CAD_GEO_SF_CONE",CADKEY,82,0x4,"Cone Surface"},
	{"CAD_GEO_SF_SPHERE",CADKEY,83,0x4,"Sphere Surface"}, 
	{"CAD_GEO_SF_TORUS",CADKEY,84,0x4,"Torus Surface"},
	{"CAD_GEO_SF_REVOLVE",CADKEY,85,0x4,"Surface of Revolution"}, 
	{"CAD_GEO_SF_TABCYL",CADKEY,86,0x4,"Tabulated Cylinder Surface"},
	{"CAD_GEO_SF_RULED",CADKEY,87,0x4,"Surface Thru 2 Entities"},
	{"CAD_GEO_SF_4CVL",CADKEY,88,0x4,"Surface by 4 CVS Lin Interp"},
	{"CAD_GEO_SF_4CVC",CADKEY,89,0x4,"Surface by 4 CVS Cub Interp"},
	{"CAD_GEO_SF_FIT",CADKEY,90,0x4,"Surface Fit Thru Entities"},
	{"CAD_GEO_SF_MODALS",CADKEY,91,0x4,"Set Surface Modals"}, 
	{"CAD_GEO_SF_ATTRIB",CADKEY,92,0x4,"Modify Surface Attribs"},
	{"CAD_GEO_SF_REVERSE",CADKEY,93,0x4,"Reverse Surface Normal"},
	{"CAD_GEO_LIGHTS_MODALS",CADKEY,94,0x4,"Light Modals"},
	{"CAD_LOAD_LIGHTS",CADKEY,95,0x4,"Load Light Settings"},
	{"CAD_LOAD_MATERIALS",CADKEY,96,0x4,"Load Material Settings"},
	{"CAD_GEO_SF_MATERIAL",CADKEY,97,0x4,"Material Modals"}, 
	{"CAD_GEO_SF_LIGHTS",CADKEY,98,0x4,"Light Modals"},
	{"CAD_REMOVE_GEO",CADKEY,99,0x14,"Remove Geometry"}, 
	{"CAD_MOD_ENTITY",CADKEY,100,0x14,"Modify Entity's Definition"},
	{"CAD_REMOVE_ALL",CADKEY,101,0x14,"Remove all Displayed Geo"},
	{"CAD_SCALE_GEO",CADKEY,102,0x14,"Apply Scale to Geometry"},
	{"CAD_SPLIT_CV",CADKEY,103,0x14,"Split Entity into 2 ents"},
	{"CAD_REVERSE_CV",CADKEY,104,0x14,"Reverse Direction of Geo"},
	{"CAD_MOVE_PTPT",CADKEY,105,0x14,"Move Geo Point to Point"},
	{"CAD_MOVE_VECTOR",CADKEY,106,0x14,"Move Geo Using Vector"},
	{"CAD_MOVE_DRAG",CADKEY,107,0x14,"Move Geo by Dragging"}, 
	{"CAD_MOVE_ROTATE",CADKEY,108,0x14,"Move Geo Using Rotation"},
	{"CAD_MOVE_MIRROR",CADKEY,109,0x14,"Move Geo Using Mirror Plane"},
	{"CAD_COPY_PTPT",CADKEY,110,0x14,"Copy geo Point to Point"},
	{"CAD_COPY_VECTOR",CADKEY,111,0x14,"Copy Geo Using Vector"}, 
	{"CAD_COPY_DRAG",CADKEY,112,0x14,"Copy Geo by Dragging"},
	{"CAD_COPY_ROTATE",CADKEY,113,0x14,"Copy Geo Using Rotation"}, 
	{"CAD_COPY_MIRROR",CADKEY,114,0x14,"Copy Geo Using Mirror Plane"},
	{"CAD_COPY_SCALE",CADKEY,115,0x14,"Copy Geo By Scale Factor"},
	{"CAD_LOAD_UNIBASE",CADKEY,116,0x6,"Load Unibase File"}, 
	{"CAD_SAVE_UNIBASE",CADKEY,117,0x6,"Save Unibase File"},
	{"CAD_MERGE_UNIBASE",CADKEY,118,0x6,"Merge Unibase into Existing"},
	{"DUMMY",CADKEY,119,0x6,"No Description"},
	{"DUMMY",CADKEY,120,0x6,"No Description"}, 
	{"DUMMY",CADKEY,121,0x6,"No Description"},
	{"DUMMY",CADKEY,122,0x6,"No Description"}, 
	{"CAD_SEL_SAVE",CADKEY,123,0x6,"Select Save of Unibase"},
	{"DUMMY",CADKEY,124,0x6,"No description"},  
	{"DUMMY",CADKEY,125,0x6,"No description"},
	{"DUMMY",CADKEY,126,0x6,"No description"}, 
	{"DUMMY",CADKEY,127,0x6,"No description"},
	{"CAD_REC_ON",CADKEY,128,0x6,"Start Recording"}, 
	{"CAD_REC_OFF",CADKEY,129,0x6,"Stop Recording"},
	{"CAD_PLAYBACK",CADKEY,130,0x6,"Start Playback"}, 
	{"DUMMY",CADKEY,131,0x6,"No description"},
	{"DUMMY",CADKEY,132,0x6,"No description"}, 
	{"DUMMY",CADKEY,133,0x6,"No description"},
	{"DUMMY",CADKEY,134,0x6,"No description"}, 
	{"DUMMY",CADKEY,135,0x6,"No description"},
	{"DUMMY",CADKEY,136,0x6,"No description"}, 
	{"DUMMY",CADKEY,137,0x6,"No description"},
	{"DUMMY",CADKEY,138,0x6,"No description"}, 
	{"DUMMY",CADKEY,139,0x6,"No description"},
	{"DUMMY",CADKEY,140,0x6,"No description"}, 
	{"DUMMY",CADKEY,141,0x6,"No description"},
	{"DUMMY",CADKEY,142,0x6,"No description"}, 
	{"DUMMY",CADKEY,143,0x6,"No description"},
	{"DUMMY",CADKEY,144,0x6,"No description"}, 
	{"DUMMY",CADKEY,145,0x6,"No description"},
	{"DUMMY",CADKEY,146,0x6,"No description"}, 
	{"DUMMY",CADKEY,147,0x6,"No description"},
	{"DUMMY",CADKEY,148,0x6,"No description"}, 
	{"DUMMY",CADKEY,149,0x6,"No description"},
	{"DUMMY",CADKEY,150,0x6,"No description"}, 
	{"DUMMY",CADKEY,151,0x6,"No description"},
	{"DUMMY",CADKEY,152,0x6,"No description"}, 
	{"DUMMY",CADKEY,153,0x6,"No description"},
	{"DUMMY",CADKEY,154,0x6,"No description"}, 
	{"DUMMY",CADKEY,155,0x6,"No description"},
	{"DUMMY",CADKEY,156,0x6,"No description"}, 
	{"DUMMY",CADKEY,157,0x6,"No description"},
	{"DUMMY",CADKEY,158,0x6,"No description"}, 
	{"DUMMY",CADKEY,159,0x6,"No description"},
	{"DUMMY",CADKEY,160,0x6,"No description"}, 
	{"DUMMY",CADKEY,161,0x6,"No description"},
	{"CAD_DRAW_ENTER",CADKEY,162,0x6,"Enter Drawing Mode"}, 
	{"CAD_DRAW_EXIT",CADKEY,163,0x10,"Exit Drawing Mode"},
	{"CAD_DRAW_CREATE",CADKEY,164,0x10,"Create Drawing"}, 
	{"CAD_DRAW_PLACEVW",CADKEY,165,0x10,"Place View on Drawing"},
	{"CAD_DRAW_VIEW",CADKEY,166,0x10,"Drawing Mode View"},
	{"CAD_DRAW_DELETE",CADKEY,167,0x10,"Delete Drawing"},
	{"CAD_DRAW_RENAME",CADKEY,168,0x10,"Rename Drawing"}, 
	{"DUMMY",CADKEY,169,0x10,"No description"},
	{"CAD_DRAW_ARCHIVE",CADKEY,170,0x10,"Archive Drawing"}, 
	{"CAD_DRAW_RETRIEVE",CADKEY,171,0x10,"Retrieve Drawing"},
/*
.....removed it because no longer  use it
.....Yurong 9/5/97
*/
	{"DUMMY",CADKEY,172,0x16,"No description"},
	{"CAD_PLOT_LOCAL",CADKEY,173,0x16,"Create Drawing Plot"}, 
	{"CAD_PLOT_SETFL",CADKEY,174,0x16,"Modify Plot Setup File"},
	{"CAD_PLOT_PENTB",CADKEY,175,0x16,"Modify Plot Pen Table File"}, 
	{"DUMMY",CADKEY,176,0x16,"No description"},
	{"DUMMY",CADKEY,177,0x16,"No description"},
	{"CAD_DRAFT_SCALE",CADKEY,178,0x14,"Set Drawing Scale"}, 
	{"CAD_DRAFT_VIEW",CADKEY,179,0x14,"Drafting Mode Viewing"},
	{"CAD_DRAFT_SAVE",CADKEY,180,0x14,"Save Drafting Standard"},
	{"CAD_DRAFT_LOAD",CADKEY,181,0x14,"Load Drafting Standard"},
	{"CAD_DRAFT_DHORIZ",CADKEY,182,0x14,"Horizontal Dimension"}, 
	{"CAD_DRAFT_DVERT",CADKEY,183,0x14,"Vertical Dimension"},
	{"CAD_DRAFT_DPARL",CADKEY,184,0x14,"Parallel Dimension"},
	{"CAD_DRAFT_DPERP",CADKEY,185,0x14,"Perpendicular Dimension"},
	{"CAD_DRAFT_DTHICK",CADKEY,186,0x14,"Thickness Dimension"},
	{"CAD_DRAFT_DANG",CADKEY,187,0x14,"Angular Dimension"},
	{"CAD_DRAFT_DARCL",CADKEY,188,0x14,"Arc Length Dimension"}, 
	{"CAD_DRAFT_DRAD",CADKEY,189,0x14,"Radius Dimension"},
	{"CAD_DRAFT_DDIA",CADKEY,190,0x14,"Diameter Dimension"}, 
	{"CAD_DRAFT_DCL",CADKEY,191,0x14,"Create Center Line"},
	{"CAD_DRAFT_DPOL",CADKEY,192,0x14,"Polar Coordinate Dimension"}, 
	{"CAD_DRAFT_ANOTE",CADKEY,193,0x14,"Create Notes"},
	{"CAD_DRAFT_ALABEL",CADKEY,194,0x14,"Create Label"},
	{"CAD_DRAFT_ATEXT",CADKEY,195,0x14,"Create Text"},
	{"CAD_DRAFT_AHATCH",CADKEY,196,0x14,"Crosshatch Area"},
	{"CAD_DRAFT_AARROW",CADKEY,197,0x14,"Create Arrowhead on Entity"},
	{"CAD_DRAFT_APOSTOL",CADKEY,198,0x14,"Set Geometric Tolerances"}, 
	{"CAD_DRAFT_ABALL",CADKEY,199,0x14,"Create Balloon"},
	{"CAD_DRAFT_REPOSIT",CADKEY,200,0x14,"Reposition Dimension"}, 
	{"CAD_DRAFT_REGEN",CADKEY,201,0x14,"Regenerate Dimension"},
	{"CAD_DRAFT_ETEXT",CADKEY,202,0x14,"Edit Text"}, 
	{"CAD_DRAFT_MTOLER",CADKEY,203,0x14,"Modify Tolerance"},
	{"CAD_DRAFT_MNTEXT",CADKEY,204,0x14,"Modify Note Text Attrib"}, 
	{"CAD_DRAFT_MDTEXT",CADKEY,205,0x14,"Modify Dimension Text Attrib"},
	{"CAD_DRAFT_MDATT",CADKEY,206,0x14,"Modify Dimension Attrib"}, 
	{"CAD_DRAFT_MARROW",CADKEY,207,0x14,"Modify Arrowhead Attributes"},
	{"CAD_DRAFT_MDLINE",CADKEY,208,0x14,"Modify Dimension Line Attrib"}, 
	{"CAD_DRAFT_MELINE",CADKEY,209,0x14,"Modify Extension Line Attrib"},
	{"CAD_DRAFT_MLEADER",CADKEY,210,0x14,"Modify Leader Line Attrib"}, 
	{"CAD_DRAFT_MHATCH",CADKEY,211,0x14,"Modify Crosshatch Attrib"},
	{"CAD_DRAFT_MCLINE",CADKEY,212,0x14,"Modify Center Line Attribute"}, 
	{"CAD_DRAFT_ONTEXT",CADKEY,213,0x14,"Note Text Modals"},
	{"CAD_DRAFT_ODTEXT",CADKEY,214,0x14,"Dimension Text Modals"}, 
	{"CAD_DRAFT_ODIM",CADKEY,215,0x14,"Dimension Modals"},
	{"CAD_DRAFT_OTOL",CADKEY,216,0x14,"Tolerance Modals"}, 
	{"CAD_DRAFT_ODLINE",CADKEY,217,0x14,"Dimension Line Modals"},
	{"CAD_DRAFT_OELINE",CADKEY,218,0x14,"Extension Line Modals"}, 
	{"CAD_DRAFT_OLEADER",CADKEY,219,0x14,"Leader Line Modals"},
	{"CAD_DRAFT_OARROW",CADKEY,220,0x14,"Arrowhead Modals"}, 
	{"CAD_DRAFT_OSPEC",CADKEY,221,0x14,"Special Drafting Modals"},
	{"CAD_DRAFTING",CADKEY,222,0x14,"No description available"}, 
	{"CAD_DRAFT_EXIT",CADKEY,223,0x14,"Exit Drafting Mode"},
	{"CAD_CALCULATOR",CADKEY,224,0x14,"Calculator"},
/*
.....NCLIPV functions
*/
	{"IPV_STOCK_BXPT",IPVKEY,0,0x142,"IPV Stock Box From 2 PTS"}, 
	{"IPV_STOCK_BXLEN",IPVKEY,1,0x142,"IPV Stk Box From CEN & LEN"},
	{"IPV_STOCK_CYLCIR",IPVKEY,2,0x142,"IPV Stock Cyl From CI & LEN"}, 
	{"IPV_STOCK_CYLPT",IPVKEY,3,0x142,"IPV Stock Cyl From 2 PTS"},
	{"IPV_STOCK_SWEEP",IPVKEY,4,0x142,"IPV Stock Profile Sweep"},
	{"IPV_STOCK_REVOLVE",IPVKEY,5,0x140, "IPV Stock Revolve"}, 
	{"IPV_FIXT_BXPT",IPVKEY,6,0x142,"IPV Fixture Box From 2 Points"}, 
	{"IPV_FIXT_BXLEN",IPVKEY,7,0x142,"IPV Fixt Box From CEN & LEN"},
	{"IPV_FIXT_CYLCIR",IPVKEY,8,0x142,"IPV Fixt Cyl From CI & LEN"}, 
	{"IPV_FIXT_CYLPT",IPVKEY,9,0x142,"IPV Fixture Cyl From 2 Pts"},
	{"IPV_FIXT_SWEEP",IPVKEY,10,0x142,"IPV Fixture Profile Sweep"},
	{"IPV_FIXT_REVOLVE",IPVKEY,11,0x140,"IPV Fixture Revolve"},
	{"IPV_INTERACTIVE",IPVKEY,12,0x42,"Interactive NCLIPV"}, 
	{"IPV_STANDALONE",IPVKEY,13,0x42,"Standalone NCLIPV"},
	{"IPV_TOOL_ON",IPVKEY,14,0x102,"Start Machining Sequence"},
	{"IPV_TOOL_OFF",IPVKEY,15,0x102,"End Machining Sequence"}, 
	{"IPV_MODALS",IPVKEY,16,0x142,"NCLIPV Modals"},
	{"IPV_VIEW_SAME",IPVKEY,17,0x140,"Change IPV View"}, 
	{"IPV_TOOL_MODALS",IPVKEY,18,0x140,"Display Tool Modals Form"},
	{"IPV_COMPARE",IPVKEY,19,0x140,"Compare Cut Surfaces"},
	{"IPV_REMOVE_CHIPS", IPVKEY,20,0x140,"Remove IPV Excess Stock"},
	{"IPV_SECTION",IPVKEY,21,0x140,"Section IPV Part"},
	{"IPV_STOCK_CONTOUR",IPVKEY,22,0x142,"IPV Stock Contour"},
	{"IPV_EXPORT_SESSION",IPVKEY,23,0x140,"Export IPV Session"}, 
	{"IPV_IMPORT_SESSION",IPVKEY,24,0x140,"Import IPV Session"},
	{"IPV_STOCK_MODALS",IPVKEY,25,0x140,"Set Stock Attributes"},
	{"IPV_FIXT_MODALS",IPVKEY,26,0x140,"Set Fixture Attributes"},
	{"IPV_STOCK_ATTRIBS",IPVKEY,27,0x140,"Modify Stock Attributes"},
	{"IPV_FIXT_ATTRIBS",IPVKEY,28,0x140,"Modify Fixture Attributes"},
	{"IPV_SAVE_STOCK",IPVKEY,29,0x140,"Save Stock & Fixture Prims"},
	{"IPV_LOAD_STOCK",IPVKEY,30,0x140,"Load Stock & Fixture Prims"},
	{"IPV_SAVE_STOCK_STL",IPVKEY,31,0x140,"Save Stock STL File"},
	{"IPV_SAVE_FIXT_STL",IPVKEY,32,0x140,"Save Fixture STL  File"},
	{"IPV_LOAD_STOCK_STL",IPVKEY,33,0x140,"Load Stock STL File"},
	{"IPV_LOAD_FIXT_STL",IPVKEY,34,0x140,"Load Fixture STL File"},
	{"IPV_STOCK_BOUND",IPVKEY,35,0x140,"IPV Stock Bounding Box"}, 
	{"IPV_TOOL_LIST",IPVKEY,36,0x140,"Edit IPV Tool List"}, 
	{"IPV_CUT_COLORS",IPVKEY,37,0x140,"Set IPV Simulation Colors"}, 
	{"IPV_MEASURE",IPVKEY,38,0x140,"Measure IPV Part"}, 
	{"IPV_SAVE_SESSION",IPVKEY,39,0x140,"Save Internal IPV Session"}, 
	{"IPV_RESTORE_SESSION",IPVKEY,40,0x140,"Restore Internal IPV Session"}, 
	{"IPV_RESET_SESSION",IPVKEY,41,0x140,"Reset IPV Session"}, 
	{"IPV_DYNAMIC_MOUSE",IPVKEY,42,0x140,"IPV Dynamic Mouse Viewing"},
	{"IPV_FIT_VIEW",IPVKEY,43,0x140,"IPV Extrema Zoom"},
	{"IPV_VIEW_X",IPVKEY,44,0x140,"IPV View along X-axis"}, 
	{"IPV_VIEW_Y",IPVKEY,45,0x140,"IPV View along Y-axis"},
	{"IPV_VIEW_Z",IPVKEY,46,0x140,"IPV View along Z-axis"}, 
	{"IPV_VIEW_NEGX",IPVKEY,47,0x140,"IPV View along negative X-axis"},
	{"IPV_VIEW_NEGY",IPVKEY,48,0x140,"IPV View along negative Y-axis"}, 
	{"IPV_VIEW_NEGZ",IPVKEY,49,0x140,"IPV View along negative Z-axis"},
	{"IPV_FLIP_VIEW",IPVKEY,50,0x140,"IPV View from opposite dir"},
	{"IPV_REPAINT_VIEW",IPVKEY,51,0x140,"IPV Repaint View"},
	{"IPV_CHANGE_VIEW",IPVKEY,52,0x140,"IPV Change View Form"}, 
	{"IPV_PREVIOUS_VIEW",IPVKEY,53,0x140,"IPV Previous View"},
	{"IPV_WINDOW_ZOOM",IPVKEY,54,0x140,"IPV Window Zoom"}, 
	{"IPV_SCALE_ZOOM",IPVKEY,55,0x140,"IPV Scale Zoom"},
	{"IPV_PAN",IPVKEY,56,0x140,"IPV Pan View"}, 
	{"IPV_VIEW_TRACUT",IPVKEY,57,0x140,"IPV View By TRACUT"},
	{"IPV_VIEW_REFSYS",IPVKEY,58,0x140,"IPV View By REFSYS"}, 
	{"IPV_VIEW_MATRIX",IPVKEY,59,0x140,"IPV View by Matrix"},
	{"IPV_VIEW_TOOL",IPVKEY,60,0x140,"IPV View Down Tool Axis"},
	{"IPV_VIEW_CENTER",IPVKEY,61,0x140,"IPV Dynamic View Center"},
	{"IPV_FIXT_CONTOUR",IPVKEY,62,0x140,"IPV Fixture Contour"},
	{"IPV_PRINT_SCREEN",IPVKEY,63,0x140,"IPV Print Screen"},
	{"IPV_DIAGNOSTICS",IPVKEY,64,0x140,"IPV Diagnostic Handler"},
	{"IPV_SWAP_SCREEN",IPVKEY,65,0x40,"Swap IPV and NCL Screens"},
	{"IPV_LOAD_MACHINE",IPVKEY,66,0x140,"Load Simulation Machine"},
	{"IPV_PLAYBACK",IPVKEY,67,0x140,"NCLIPV Playback Form"},
	{"DUMMY",IPVKEY,68,0x40,"Not Used."},
	{"IPV_REGION",IPVKEY,69,0x140,"IPV Region of Interest"},
	{"IPV_DISPLAY_PROP",IPVKEY,70,0x140,"IPV Display Properties"},
	{"IPV_LIGHTS",IPVKEY,71,0x140,"IPV Light Modals"},
	{"IPV_STOCK_CONPT",IPVKEY,72,0x142,"IPV Stock Cone From 2 PTS"},
	{"IPV_STOCK_CONCE",IPVKEY,73,0x142,"IPV Stock Cone From Center"},
	{"IPV_STOCK_CYLCE",IPVKEY,74,0x142,"IPV Stock Cyl From Center"},
	{"IPV_STOCK_SPHCI",IPVKEY,75,0x142,"IPV Stock Sphere From Circle"},
	{"IPV_STOCK_SPHCE",IPVKEY,76,0x142,"IPV Stock Sphere From Center"},
	{"IPV_STOCK_TORCI",IPVKEY,77,0x142,"IPV Stock Torus From Circle"},
	{"IPV_STOCK_TORRA",IPVKEY,78,0x142,"IPV Stock Torus Circle/Radius"},
	{"IPV_STOCK_TORCE",IPVKEY,79,0x142,"IPV Stock Torus From Center"},
	{"IPV_STOCK_SOLID",IPVKEY,80,0x142,"IPV Stock From Solid"},
	{"IPV_FIXT_CONPT",IPVKEY,81,0x142,"IPV Fixt Cone From 2 PTS"},
	{"IPV_FIXT_CONCE",IPVKEY,82,0x142,"IPV Fixt Cone From Center"},
	{"IPV_FIXT_CYLCE",IPVKEY,83,0x142,"IPV Fixt Cyl From Center"},
	{"IPV_FIXT_SPHCI",IPVKEY,84,0x142,"IPV Fixt Sphere From Circle"},
	{"IPV_FIXT_SPHCE",IPVKEY,85,0x142,"IPV Fixt Sphere From Center"},
	{"IPV_FIXT_TORCI",IPVKEY,86,0x142,"IPV Fixt Torus From Circle"},
	{"IPV_FIXT_TORRA",IPVKEY,87,0x142,"IPV Fixt Torus Circle/Radius"},
	{"IPV_FIXT_TORCE",IPVKEY,88,0x142,"IPV Fixt Torus From Center"},
	{"IPV_FIXT_SOLID",IPVKEY,89,0x142,"IPV Fixture From Solid"},
	{"IPV_APP_EXIT",IPVKEY,90,0x142,"Exit NCLIPV Application"},
	{"NCLIPV_RESTART",IPVKEY,91,0x140,"Restart NCLIPV"},
	{"NCLIPV_SET_INCH",IPVKEY,92,0x140,"Set Units Inches"},
	{"NCLIPV_SET_MM",IPVKEY,93,0x140,"Set Units Millimeters"},
	{"IPV_STEP_BACKWARD",IPVKEY,94,0x142,"IPV Step Tool Backward"},
	{"IPV_STEP_FORWARD",IPVKEY,95,0x142,"IPV Step Tool Forward"},
	{"IPV_STEP_BEGIN",IPVKEY,96,0x142,"IPV Step Tool to Beginning"},
	{"IPV_STEP_END",IPVKEY,97,0x142,"IPV Step Tool to End"},
	{"IPV_STEP_RESET",IPVKEY,98,0x142,"Reset IPV Undo Stack"},
	{"IPV_STEP_MODALS",IPVKEY,99,0x142,"IPV Motion Undo Settings"},
	{"IPV_STEP_FACE",IPVKEY,100,0x142,"IPV Step Tool to Face"},
/*
.....MSL functions
*/
	{"MSL_EXIT",MSLKEY,0,0x40,"Exit MS Lite"},
	{"MSL_VIEW_FRONT",MSLKEY,1,0x40,"View Front"},
	{"MSL_VIEW_BACK",MSLKEY,2,0x40,"View Back"},
	{"MSL_VIEW_TOP",MSLKEY,3,0x40,"View Top"},
	{"MSL_VIEW_BOTTOM",MSLKEY,4,0x40,"View Bottom"},
	{"MSL_VIEW_LEFT",MSLKEY,5,0x40,"View Left"},
	{"MSL_VIEW_RIGHT",MSLKEY,6,0x40,"View Right"},
	{"MSL_VIEW_ISOMETRIC",MSLKEY,7,0x40,"View Isometric"},
	{"MSL_VIEW_PREV",MSLKEY,8,0x40,"Previous View"},
	{"MSL_VIEW_RESET",MSLKEY,9,0x40,"View Reset"},
	{"MSL_LOAD_MACHINE",MSLKEY,10,0x40,"Load Machine"},
	{"MSL_MACHINE_ATTR",MSLKEY,11,0x40,"Machine Attributes Form"},
	{"MSL_FIT_VIEW",MSLKEY,12,0x40,"Extrema Zoom"},
	{"MSL_DYNAMIC",MSLKEY,13,0x40,"Dynamic Mouse View"},
	{"MSL_DYNCEN",MSLKEY,14,0x40,"Dynamic View Center"},
	{"MSL_WINDOW",MSLKEY,15,0x40,"Window Zoom"},
	{"MSL_DIAGNOSTICS",MSLKEY,16,0x40,"Clash Diagnostic"},
	{"MSL_SIMULATION",MSLKEY,17,0x40,"Machine Simulation"},
	{"MSL_ABOUT",MSLKEY,18,0x40,"Machine Simulation"},
/*
.....End of function defintions
*/
	{"~END~",CADKEY,1000,0x0, "End of functions"}
};

UZ_statcalls UZ_statfuncs[] =
{
	{"NCLMODE", 0, "NCL_SELECT_MODE"},
	{"DRAFT_SCALE",1,"CAD_DRAFT_SCALE"},
	{"UNITS",2, "NCL_UNITS"},
	{"LAYER",3, "NCL_INPUT_LAYER"},
	{"REDEF",4, "NCL_NAME_MODALS"},
	{"DIRECTORY",5,"CAM_LOAD_PP"},
	{"PROGRAM",6,"CAM_LOAD_PP"},
	{"UNIBASE",7,"CAD_LOAD_UNIBASE"},
	{"INPUT_MODE", 8, "CAM_TEXT_MODE"},
	{"PROCESS_MODE",9, "CAM_COMMAND"},
	{"REFSYS",10, "CAM_REFSYS"},
	{"MODSYS",11,"CAM_MODSYS"},
	{"TRACUT",12,"CAM_TRACUT"},
	{"FEDRAT",13, "CAM_FEDRAT"},
	{"TOLER",14,"CAM_MOTION_CALC"},
	{"THICK",15,"CAM_MOTION_CALC"},
	{"TOOL_ENDPT",16, "CAM_GOTO"},
	{"TLAXIS",17,"CAM_TLAXIS"},
	{"TLAXIS_MODE",18,"CAM_TLAXIS"},
	{"SEQUNC",19,"sequnc.menu"},
	{"TIME",20, "NCL_UPDATE_TIME"},
	{"~END~",1000,"KEY_NOOP"},
};

int UZ_status_table[UZ_MAX_STATNAME][MAX_STAT_FUNC];
int UZ_dials,UZ_buttons;

#else
#ifdef EXT
#undef EXT
#endif
#ifdef __cplusplus 
#define EXT extern "C"
#else
#define EXT extern
#endif
EXT UZ_keytable UZ_niskeytab[],UZ_nisfkeytab[],UZ_nisbkeytab[];
EXT UZ_keytable UZ_camkeytab[],UZ_camfkeytab[],UZ_cambkeytab[];
EXT UZ_keytable UZ_cadkeytab[],UZ_cadfkeytab[],UZ_cadbkeytab[];
EXT UZ_keytable UZ_ipvkeytab[],UZ_ipvfkeytab[],UZ_ipvbkeytab[];
EXT char *zfkeysym[];
EXT char *UZ_daskey[];
EXT UZ_keycalls UZ_keyfuncs[];
EXT UZ_statcalls UZ_statfuncs[];
EXT int UZ_status_table[UZ_MAX_STATNAME][MAX_STAT_FUNC];
EXT int UZ_dials,UZ_buttons;
EXT UZ_functable UZ_itemcalls[UZ_MAX_MENUITEM];
EXT int UZ_item_count;
EXT UZ_functable UZ_accelcalls[UZ_MAX_KEYITEM];
EXT int UZ_accel_count;
EXT int UZ_menucalls[UZ_MAX_MENU];
EXT int UZ_menu_count;
EXT char UZ_mouse_function[20][80];
#undef EXT
#endif

