C        IMPLICIT STATEMENT FOR ALL SUBROUTINES USING INTEGER*2 DATA
 
C*     MODULE NAME AND RELEASE LEVEL 
C*       ncq502.com , 25.1
C*    DATE AND TIME OF LAST  MODIFICATION
C*       04/29/15 , 15:07:32

C DEC-START
      IMPLICIT INTEGER*2(I-N)
C DEC-END
 
C
      COMMON /LOGSSQ/ LINBUF
C
      CHARACTER*80 LINBUF
