/*********************************************************************
**    NAME         :  nkeywd.h
**       CONTAINS: NCL key word definitions.
**    COPYRIGHT 1984 (c) UNICAD Inc.  All Rights Reserved.
**     MODULE NAME AND RELEASE LEVEL 
**       nkeywd.h , 25.3
**    DATE AND TIME OF LAST  MODIFICATION
**       05/04/15 , 11:21:00
*********************************************************************/
/*
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!                                                             !!!!!!
!!!!!!   NOTE:                                                     !!!!!!
!!!!!!      Recompile routine NEGLOBAL.C to cause any changes      !!!!!!
!!!!!!      made in this include file to be reflected in the       !!!!!!
!!!!!!      executable.                                            !!!!!!
!!!!!!                                                             !!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

#ifndef NCL_NKEYWD

#ifdef NCL_MPGM

char NCL_anote[] = "ANOTE/";
char NCL_an[] = "ANOTE";
char NCL_pt[] = "POINT/";
char NCL_point[] = "POINT";
char NCL_pv[] = "PNTVEC/";
char NCL_pntvec[] = "PNTVEC";
char NCL_ve[] = "VECTOR/";
char NCL_vector[] = "VECTOR";
char NCL_ln[] = "LINE/";
char NCL_line[] = "LINE";
char NCL_pl[] = "PLANE/";
char NCL_place[] = "PLACE/";
char NCL_decomp[] = "DECOMP/";
char NCL_lace[] = "LACE";
char NCL_plane[] = "PLANE";
char NCL_ci[] = "CIRCLE/";
char NCL_circle[] = "CIRCLE";
char NCL_cv[] = "CURVE/";
char NCL_curve[] = "CURVE";
char NCL_data[] = "DATA/";
char NCL_sf[] = "SURF/";
char NCL_surf[] = "SURF";
char NCL_mx[] = "MATRIX/";
char NCL_matrix[] = "MATRIX";
char NCL_sh[] = "SHAPE/";
char NCL_shape[] = "SHAPE";
char NCL_so[] = "SOLID/";
char NCL_solid[] = "SOLID";
char NCL_pn[] = "PATERN/";
char NCL_patern[] = "PATERN";
char NCL_all[] = "ALL";
char NCL_nsh[] = "NSHAPE/";
char NCL_rename[] = "RENAME/";
char NCL_percnt[] = "PERCNT";

char NCL_letter[] = "LETTER";
char NCL_linear[] = "LINEAR";
char NCL_arc[] = "ARC";
char NCL_random[] = "RANDOM";

char NCL_dist[] = "=DIST/";
char NCL_zsurf[] = "ZSURF/";
char NCL_refsys[] = "REFSYS/";
char NCL_genpts[] = "GENPTS/";
char NCL_can[] = "=CAN(";
char NCL_dot[] = "=DOT(";
char NCL_sqrt[] = "=SQRT(";
char NCL_log[] = "=LOG(";
char NCL_abs[] = "=ABS(";
char NCL_sin[] = "=SIN(";
char NCL_asin[] = "=ASIN(";
char NCL_cos[] = "=COS(";
char NCL_acos[] = "=ACOS(";
char NCL_tan[] = "=TAN(";
char NCL_atan[] = "=ATAN(";
char NCL_atan2[] = "=ATAN2(";
char NCL_int[] = "=INT(";
char NCL_num[] = "=NUM(";
char NCL_analyz[] = "ANALYZ/";

char NCL_cutter[] = "CUTTER/";
char NCL_psis[] = "PSIS/";
char NCL_indirp[] = "INDIRP/";
char NCL_indirv[] = "INDIRV/";
char NCL_indirv_posx[] = "INDIRV/1,0,0";
char NCL_indirv_posy[] = "INDIRV/0,1,0";
char NCL_indirv_posz[] = "INDIRV/0,0,1";
char NCL_indirv_negx[] = "INDIRV/-1,0,0";
char NCL_indirv_negy[] = "INDIRV/0,-1,0";
char NCL_indirv_negz[] = "INDIRV/0,0,-1";
char NCL_goto[] = "GOTO/";
char NCL_go[] = "GO/";
char NCL_godlta[] = "GODLTA/";
char NCL_gofwd[] = "GOFWD/";
char NCL_gofwda[] = "GOFWDA/";
char NCL_gofwd_ln_fwd[] = "GOFWD/(LINE/FWD)";
char NCL_golft[] = "GOLFT/";
char NCL_gorgt[] = "GORGT/";
char NCL_goback[] = "GOBACK/";
char NCL_godown[] = "GODOWN/";
char NCL_goup[] = "GOUP/";
char NCL_nops[] = "NOPS";
char NCL_autops[] = "AUTOPS";
char NCL_profil[] = "PROFIL/";
char NCL_clrsrf[] = "CLRSRF";
char NCL_deep[] = "DEEP";
char NCL_rtrcto[] = "RTRCTO";
char NCL_cut1[] = "CUT";
char NCL_dntcut[] = "DNTCUT/";
char NCL_multax_on[] = "MULTAX/ON";
char NCL_multax_off[] = "MULTAX/OFF";
char NCL_contct_on[] = "CONTCT/ON";
char NCL_contct_off[] = "CONTCT/OFF";
char NCL_srfvct[] = "SRFVCT/";
char NCL_tracut[] = "TRACUT/";
char NCL_mtracut[] = "TRACUT";
char NCL_fedrat[] = "FEDRAT/";
char NCL_feedrat[] = "FEDRAT";
char NCL_rapid[] = "RAPID";
char NCL_index[] = "INDEX/";
char NCL_both[] = "BOTH";
char NCL_scrub0[] = "SCRUB";
char NCL_scrub[] = "SCRUB/";
char NCL_pocket[] = "POCKET/";
char NCL_vmpock[] = "VMPOCK/";
char NCL_vmpmod[] = "VMPMOD/";
char NCL_flutes[] = "FLUTES";
char NCL_side[] = "SIDE";
char NCL_slot[] = "SLOT";
char NCL_spindl[] = "SPINDL";
char NCL_dwell[] = "DWELL";
char NCL_tlaxis[] = "TLAXIS/";
char NCL_from[] = "FROM/";
char NCL_parelm[] = "PARELM";
char NCL_last[] = "LAST";
char NCL_copy1[] = "COPY/";
char NCL_remove[] = "REMOVE/";
char NCL_redef[] = "REDEF/";
char NCL_move[] = "MOVE/";
char NCL_clone[] = "CLONE/";
char NCL_rmill[] = "RMILL/";
/*  added by kathy */
char NCL_lathe[] = "LATHE/";
char NCL_invis[] = "*INVIS/";
char NCL_visibl[] = "*VISIBL/";
char NCL_disply[] = "*DISPLY/";
char NCL_revers[] = "REVERS/";
char NCL_end[] = "END";
char NCL_combin[] = "COMBIN";
char NCL_guide[] = "GUIDE";

char NCL_rough[] = "ROUGH";
char NCL_cldist[] = "CLDIST";
char NCL_stock[] = "STOCK";
char NCL_depth[] = "DEPTH";
char NCL_cutang[] = "CUTANG";
char NCL_retrct[] = "RETRCT";
char NCL_return[] = "RETURN";
char NCL_finish[] = "FINISH";
char NCL_engage[] = "ENGAGE";

char NCL_thru[] = "THRU";
char NCL_nomore[] = "NOMORE";
char NCL_te[] = "TE";
char NCL_ve_tlaxis[] = "TLAXIS";
char NCL_center[] = "CENTER";
char NCL_intof[] = "INTOF";
char NCL_atangl[] = "ATANGL";
char NCL_endpt[] = "ENDPT";
char NCL_parlel[] = "PARLEL";
char NCL_perpto[] = "PERPTO";
char NCL_tanto[] = "TANTO";
char NCL_pstan[] = "PSTAN";
char NCL_fwd[] = "FWD";
char NCL_radius[] = "RADIUS";
char NCL_canon[] = "CANON";
char NCL_canon1[] = "CANON/";
char NCL_unit[] = "UNIT";
char NCL_invers[] = "INVERS";
char NCL_mirror1[] = "MIRROR";
char NCL_length[] = "LENGTH";
char NCL_rotate[] = "ROTATE";
char NCL_scale1[] = "SCALE";
char NCL_trans[] = "TRANS";
char NCL_island[] = "ISLAND";
char NCL_transl[] = "TRANSL";
char NCL_fit[] = "FIT,";
char NCL_conic[] = "CONIC,";
char NCL_compos[] = "COMPOS,";
char NCL_mesh[] = "MESH";
char NCL_quilt[] = "QUILT";
char NCL_offset[] = "OFFSET";
char NCL_netsf[] = "NETSF";
char NCL_part[] = "PART";
char NCL_at[] = "AT";
char NCL_same[] = "SAME";
char NCL_scale[] = "SCALE";
char NCL_modify[] = "MODIFY";
char NCL_xyrot[] = "XYROT";
char NCL_yzrot[] = "YZROT";
char NCL_zxrot[] = "ZXROT";
char NCL_ps[] = "PS";
char NCL_ds[] = "DS";
char NCL_cs[] = "CS";
char NCL_fan[] = "FAN";
char NCL_normal[] = "NORMAL";
char NCL_ipm[] = "IPM";
char NCL_ipr[] = "IPR";
char NCL_mmpm[] = "MMPM";
char NCL_mmpr[] = "MMPR";
char NCL_once[] = "ONCE";
char NCL_continuous[] = "CONTINUOUS";
char NCL_ramp[] = "RAMP";
char NCL_plunge[] = "PLUNGE";
char NCL_sharp[] = "SHARP";
char NCL_helix[] = "HELIX";
char NCL_cycle[] = "CYCLE";
char NCL_couple[] = "COUPLE";
char NCL_pokmod[] = "POKMOD/";

char NCL_calls[] = "CALL/";
char NCL_cmd_call1[] = "CALL";
char NCL_fini[] = "FINI";
char NCL_if[] = "IF ";
char NCL_jumpto[] = "JUMPTO/";
char NCL_loopnd[] = "LOOPND";
char NCL_loopst[] = "LOOPST";
char NCL_termac[] = "TERMAC";
char NCL_doloop[] = "DO/";
char NCL_incr[] = "INCR,";
char NCL_undo[] = "UNDO";

char NCL_src_edit[] = "*EDIT/";
char NCL_src_delete[] = "*DELETE/";
char NCL_src_find[] = "*FIND/";
char NCL_src_findtk[] = "*FINDTK/";
char NCL_src_input[] = "*INPUT";
char NCL_src_insert[] = "*INSERT";
char NCL_src_consol[] = "*CONSOL";
char NCL_src_skip[] = "*SKIP/";
char NCL_src_skip_p1[] = "*SKIP/1";
char NCL_src_skip_n1[] = "*SKIP/-1";
char NCL_show[] = "*SHOW/";
char NCL_set[] = "*SET/";
char NCL_set1[] = "**SET/";
char NCL_reset[] = "*RESET/";
char NCL_run[] = "*RUN/";
char NCL_ca[] = "CA/";
char NCL_cmd_run[] = "*RUN";
char NCL_cmd_motion[] = "MOTION";
char NCL_cmd_tapeft[] = "TAPEFT";
char NCL_cmd_adispl[] = "ADISPL";
char NCL_cmd_disply[] = "DISPLY";
char NCL_cmd_aptsrc[] = "APTSRC";
char NCL_cmd_stop[] = "STOP";
char NCL_cmd_pause[] = "PAUSE";
char NCL_cmd_case[]  = "CASE";
char NCL_circul[] = "CIRCUL";
char NCL_ipv[] = "IPV";
char NCL_remark[] = "REMARK";
char NCL_verify[] = "VERIFY";
char NCL_autouv[] = "AUTOUV";
char NCL_apt[] = "APT";
char NCL_ncl[] = "NCL";
char NCL_pprint[] = "PPRINT";
char NCL_up[] = "UP";
char NCL_down[] = "DOWN";
char NCL_to[] = "TO";
char NCL_scroll[] = "S";
char NCL_autost[] = "AUTOST";
char NCL_cirapt[] = "CIRAPT";
char NCL_indent[] = "INDENT";
char NCL_indent_all[] = "ALL";
char NCL_indent_sep[] = "SEP";
char NCL_indent_off[] = "OFF"; /* added of kathy */
char NCL_run_eof[] = "EOF";
char NCL_run_step[] = "STEP";
char NCL_show_cutter[] = "CUTTER";
char NCL_maxang[] = "MAXANG/";
char NCL_maxdp[] = "MAXDP/";
char NCL_numpts[] = "NUMPTS/";
char NCL_thick[] = "THICK/";
char NCL_toler[] = "TOLER/";
char NCL_gougck[] = "GOUGCK/";
char NCL_gougck1[] = "GOUGCK";
char NCL_gougck_on[] = "GOUGCK/ON";
char NCL_gougck_off[] = "GOUGCK/OFF";
char NCL_show_thick[] = "THICK";
char NCL_show_toler[] = "TOLER";
char NCL_show_tool[] = "TOOL";
char NCL_show_modals[] = "MODALS";
char NCL_show_source[] = "SOURCE";
char NCL_show_files[] = "FILES";
char NCL_xlarge[] = "XLARGE";
char NCL_xsmall[] = "XSMALL";
char NCL_ylarge[] = "YLARGE";
char NCL_ysmall[] = "YSMALL";
char NCL_zlarge[] = "ZLARGE";
char NCL_zsmall[] = "ZSMALL";
char NCL_posx[] = "POSX";
char NCL_negx[] = "NEGX";
char NCL_posy[] = "POSY";
char NCL_negy[] = "NEGY";
char NCL_posz[] = "POSZ";
char NCL_negz[] = "NEGZ";
char NCL_right[] = "RIGHT";
char NCL_left[] = "LEFT";
char NCL_xaxis[] = "XAXIS";
char NCL_yaxis[] = "YAXIS";
char NCL_large[] = "LARGE";
char NCL_small[] = "SMALL";
char NCL_in[] = "IN";
char NCL_out[] = "OUT";
char NCL_cross[] = "CROSS";
char NCL_plus[] = "PLUS";
char NCL_minus[] = "MINUS";
char NCL_on[] = "ON";
char NCL_past[] = "PAST";
char NCL_nearpt[] = "NEARPT";
char NCL_tllft[] = "TLLFT";
char NCL_tlon[] = "TLON";
char NCL_tlrgt[] = "TLRGT";
char NCL_tlofps[] = "TLOFPS";
char NCL_tlonps[] = "TLONPS";
char NCL_clw[] = "CLW";
char NCL_ccw[] = "CCLW";
char NCL_cmd_label[] = "LABEL";
char NCL_unitsmm[] = "UNITS/MM";
char NCL_unitsin[] = "UNITS/INCHES";
char NCL_mm[] = "MM";
char NCL_inches[] = "INCHES";
char NCL_times[] = "TIMES";
char NCL_const[] = "CONST";
char NCL_avoid[] = "AVOID";
char NCL_find[] = "FIND";
char NCL_check[] = "CHECK";
char NCL_look[] = "LOOK";
char NCL_retain[] = "RETAIN";
char NCL_omit[] = "OMIT";
char NCL_erase_motion[] = "*ERASE/MOTION";
char NCL_system[] = "*SYSTEM";
char NCL_edit[] = "*EDT";
char NCL_quit[] = "*QUIT";
char NCL_fillet[] = "FILLET";
char NCL_close[] = "CLOSE";
char NCL_open[] = "OPEN";
char NCL_contct[] = "CONTCT";
char NCL_contour[] = "CONTUR";
char NCL_spline[] = "SPLINE/";
char NCL_nsf[] = "NSURF/";
char NCL_edge[] = "EDGE";
char NCL_revolv[] = "REVOLV";
char NCL_radial[] = "RADIAL";
char NCL_modsys[] = "MODSYS/";
char NCL_ssplin[] = "SSPLIN/";
char NCL_base[] = "BASE";
char NCL_face[] = "FACE";
char NCL_trimmed[] = "TRIMMED";
char NCL_defalt[] = "DEFALT";
char NCL_scheck[] = "SCHECK";
char NCL_arcslp[] = "ARCSLP/";
char NCL_warn[]   = "WARN";
char NCL_nowarn[] = "NOWARN";
char NCL_wrap[]   = "WRAP";
char NCL_projct[] = "PROJCT";
char NCL_start[]  = "START";
char NCL_middle[] = "MIDDLE";
char NCL_cutcom[] = "CUTCOM";
char NCL_error[] = "ERROR";
char NCL_draft[] = "DRAFT/";
char NCL_layer[] = "LAYER=";
char NCL_lock[]   = "LOCK";
char NCL_interp[] = "INTERP";
char NCL_smooth[] = "SMOOTH";
char NCL_off[]    = "OFF";
char NCL_auto[]   = "AUTO";
char NCL_fmill[]  = "FMILL/";
char NCL_height[] = "HEIGHT";
char NCL_pass[]   = "PASS";
char NCL_rapto[]  = "RAPTO";
char NCL_xyplan[]  = "XYPLAN";
char NCL_yzplan[]  = "YZPLAN";
char NCL_zxplan[]  = "ZXPLAN";
char NCL_smill[]  = "SMILL/";

char NCL_box[] = "BOX";
char NCL_cone[] = "CONE";
char NCL_cylinder[] = "CYLNDR";
char NCL_sphere[] = "SPHERE";
char NCL_torus[] = "TORUS";
char NCL_extrud[] = "EXTRUD";
char NCL_level[] = "LEVEL";
char NCL_prof[] = "PROFIL";
char NCL_load[] = "LOAD";
char NCL_trform[] = "TRFORM";
char NCL_save[] = "SAVE/";
char NCL_fixtur[] = "FIXTUR";
char NCL_bound[] = "BOUND";
char NCL_stl[] = "STL";

#else

extern char NCL_anote[];
extern char NCL_an[];
extern char NCL_pt[];
extern char NCL_point[];
extern char NCL_pv[];
extern char NCL_pntvec[];
extern char NCL_ve[];
extern char NCL_vector[];
extern char NCL_ln[];
extern char NCL_line[];
extern char NCL_pl[];
extern char NCL_place[];
extern char NCL_decomp[];
extern char NCL_lace[];
extern char NCL_plane[];
extern char NCL_ci[];
extern char NCL_circle[];
extern char NCL_cv[];
extern char NCL_curve[];
extern char NCL_data[];
extern char NCL_sf[];
extern char NCL_surf[];
extern char NCL_mx[];
extern char NCL_matrix[];
extern char NCL_sh[];
extern char NCL_shape[];
extern char NCL_so[];
extern char NCL_solid[];
extern char NCL_pn[];
extern char NCL_patern[];
extern char NCL_all[];
extern char NCL_nsh[];
extern char NCL_rename[];
extern char NCL_percnt[];

extern char NCL_letter[];
extern char NCL_linear[];
extern char NCL_arc[];
extern char NCL_random[];

extern char NCL_dist[];
extern char NCL_zsurf[];
extern char NCL_refsys[];
extern char NCL_genpts[];
extern char NCL_can[];
extern char NCL_dot[];
extern char NCL_sqrt[];
extern char NCL_log[];
extern char NCL_abs[];
extern char NCL_sin[];
extern char NCL_asin[];
extern char NCL_cos[];
extern char NCL_acos[];
extern char NCL_tan[];
extern char NCL_atan[];
extern char NCL_atan2[];
extern char NCL_int[];
extern char NCL_num[];
extern char NCL_analyz[];

extern char NCL_cutter[];
extern char NCL_psis[];
extern char NCL_indirp[];
extern char NCL_indirv[];
extern char NCL_indirv_posx[];
extern char NCL_indirv_posy[];
extern char NCL_indirv_posz[];
extern char NCL_indirv_negx[];
extern char NCL_indirv_negy[];
extern char NCL_indirv_negz[];
extern char NCL_goto[];
extern char NCL_go[];
extern char NCL_godlta[];
extern char NCL_gofwd[];
extern char NCL_gofwda[];
extern char NCL_gofwd_ln_fwd[];
extern char NCL_golft[];
extern char NCL_gorgt[];
extern char NCL_goback[];
extern char NCL_godown[];
extern char NCL_goup[];
extern char NCL_nops[];
extern char NCL_autops[];
extern char NCL_profil[];
extern char NCL_clrsrf[];
extern char NCL_deep[];
extern char NCL_rtrcto[];
extern char NCL_cut1[];
extern char NCL_dntcut[];
extern char NCL_multax_on[];
extern char NCL_multax_off[];
extern char NCL_contct_on[];
extern char NCL_contct_off[];
extern char NCL_srfvct[];
extern char NCL_tracut[];
extern char NCL_mtracut[];
extern char NCL_fedrat[];
extern char NCL_feedrat[];
extern char NCL_rapid[];
extern char NCL_index[];
extern char NCL_both[];
extern char NCL_scrub0[];
extern char NCL_scrub[];
extern char NCL_pocket[];
extern char NCL_vmpock[];
extern char NCL_vmpmod[];
extern char NCL_flutes[];
extern char NCL_side[];
extern char NCL_slot[];
extern char NCL_spindl[];
extern char NCL_dwell[];
extern char NCL_tlaxis[];
extern char NCL_parelm[];
extern char NCL_last[];
extern char NCL_from[];
extern char NCL_copy1[];
extern char NCL_remove[];
extern char NCL_redef[];
extern char NCL_move[];
extern char NCL_clone[];
extern char NCL_rmill[];
/* added by kathy */
extern char NCL_lathe[];
extern char NCL_invis[];
extern char NCL_visibl[];
extern char NCL_disply[];
extern char NCL_end[];
extern char NCL_revers[];
extern char NCL_combin[];
extern char NCL_guide[];

extern char NCL_rough[];
extern char NCL_cldist[];
extern char NCL_stock[];
extern char NCL_depth[];
extern char NCL_cutang[];
extern char NCL_retrct[];
extern char NCL_return[];
extern char NCL_finish[];
extern char NCL_engage[];

extern char NCL_thru[];
extern char NCL_nomore[];
extern char NCL_te[];
extern char NCL_ve_tlaxis[];
extern char NCL_center[];
extern char NCL_intof[];
extern char NCL_atangl[];
extern char NCL_endpt[];
extern char NCL_parlel[];
extern char NCL_perpto[];
extern char NCL_tanto[];
extern char NCL_pstan[];
extern char NCL_fwd[];
extern char NCL_radius[];
extern char NCL_canon[];
extern char NCL_canon1[];
extern char NCL_unit[];
extern char NCL_invers[];
extern char NCL_mirror1[];
extern char NCL_length[];
extern char NCL_rotate[];
extern char NCL_scale1[];
extern char NCL_trans[];
extern char NCL_island[];
extern char NCL_transl[];
extern char NCL_fit[];
extern char NCL_conic[];
extern char NCL_compos[];
extern char NCL_mesh[];
extern char NCL_quilt[];
extern char NCL_offset[];
extern char NCL_part[];
extern char NCL_netsf[];

extern char NCL_calls[];
extern char NCL_cmd_call1[];
extern char NCL_fini[];
extern char NCL_if[];
extern char NCL_jumpto[];
extern char NCL_loopnd[];
extern char NCL_loopst[];
extern char NCL_termac[];
extern char NCL_doloop[];
extern char NCL_incr[];
extern char NCL_undo[];
extern char NCL_at[];
extern char NCL_same[];
extern char NCL_scale[];
extern char NCL_modify[];
extern char NCL_xyrot[];
extern char NCL_yzrot[];
extern char NCL_zxrot[];
extern char NCL_ps[];
extern char NCL_ds[];
extern char NCL_cs[];
extern char NCL_fan[];
extern char NCL_normal[];
extern char NCL_ipm[];
extern char NCL_ipr[];
extern char NCL_mmpm[];
extern char NCL_mmpr[];
extern char NCL_once[];
extern char NCL_continuous[];

extern char NCL_src_edit[];
extern char NCL_src_delete[];
extern char NCL_src_find[];
extern char NCL_src_findtk[];
extern char NCL_src_input[];
extern char NCL_src_insert[];
extern char NCL_src_consol[];
extern char NCL_src_skip[];
extern char NCL_src_skip_p1[];
extern char NCL_src_skip_n1[];
extern char NCL_show[];
extern char NCL_set[];
extern char NCL_set1[];
extern char NCL_reset[];
extern char NCL_run[];
extern char NCL_ca[];
extern char NCL_cmd_run[];
extern char NCL_cmd_motion[];
extern char NCL_cmd_tapeft[];
extern char NCL_cmd_adispl[];
extern char NCL_cmd_disply[];
extern char NCL_cmd_aptsrc[];
extern char NCL_cmd_stop[];
extern char NCL_cmd_pause[];
extern char NCL_cmd_case[];
extern char NCL_circul[];
extern char NCL_ipv[];
extern char NCL_remark[];
extern char NCL_verify[];
extern char NCL_autouv[];
extern char NCL_apt[];
extern char NCL_ncl[];
extern char NCL_pprint[];
extern char NCL_up[];
extern char NCL_down[];
extern char NCL_to[];
extern char NCL_scroll[];
extern char NCL_autost[];
extern char NCL_cirapt[];
extern char NCL_indent[];
extern char NCL_indent_all[];
extern char NCL_indent_sep[];
extern char NCL_indent_off[];
extern char NCL_run_eof[];
extern char NCL_run_step[];
extern char NCL_show_cutter[];
extern char NCL_cutcom[];
extern char NCL_error[];
extern char NCL_draft[];
extern char NCL_layer[];
extern char NCL_maxang[];
extern char NCL_maxdp[];
extern char NCL_numpts[];
extern char NCL_thick[];
extern char NCL_toler[];
extern char NCL_gougck[];
extern char NCL_gougck1[];
extern char NCL_gougck_on[];
extern char NCL_gougck_off[];
extern char NCL_show_thick[];
extern char NCL_show_toler[];
extern char NCL_show_tool[];
extern char NCL_show_modals[];
extern char NCL_show_source[];
extern char NCL_show_files[];
extern char NCL_xlarge[];
extern char NCL_xsmall[];
extern char NCL_ylarge[];
extern char NCL_ysmall[];
extern char NCL_zlarge[];
extern char NCL_zsmall[];
extern char NCL_posx[];
extern char NCL_negx[];
extern char NCL_posy[];
extern char NCL_negy[];
extern char NCL_posz[];
extern char NCL_negz[];
extern char NCL_right[];
extern char NCL_left[];
extern char NCL_xaxis[];
extern char NCL_yaxis[];
extern char NCL_large[];
extern char NCL_small[];
extern char NCL_in[];
extern char NCL_out[];
extern char NCL_cross[];
extern char NCL_plus[];
extern char NCL_minus[];
extern char NCL_on[];
extern char NCL_past[];
extern char NCL_nearpt[];
extern char NCL_tllft[];
extern char NCL_tlon[];
extern char NCL_tlrgt[];
extern char NCL_tlofps[];
extern char NCL_tlonps[];
extern char NCL_clw[];
extern char NCL_ccw[];
extern char NCL_cmd_label[];
extern char NCL_unitsmm[];
extern char NCL_unitsin[];
extern char NCL_mm[];
extern char NCL_inches[];
extern char NCL_times[];
extern char NCL_const[];
extern char NCL_avoid[];
extern char NCL_find[];
extern char NCL_check[];
extern char NCL_look[];
extern char NCL_retain[];
extern char NCL_omit[];
extern char NCL_erase_motion[];
extern char NCL_system[];
extern char NCL_edit[];
extern char NCL_quit[];
extern char NCL_fillet[];
extern char NCL_arcslp[];
extern char NCL_ramp[];
extern char NCL_plunge[];
extern char NCL_sharp[];
extern char NCL_helix[];
extern char NCL_cycle[];
extern char NCL_couple[];
extern char NCL_pokmod[];
extern char NCL_close[];
extern char NCL_open[];
extern char NCL_contct[];
extern char NCL_contour[];
extern char NCL_spline[];
extern char NCL_nsf[];
extern char NCL_edge[];
extern char NCL_revolv[];
extern char NCL_radial[];
extern char NCL_modsys[];
extern char NCL_ssplin[];
extern char NCL_base[];
extern char NCL_face[];
extern char NCL_trimmed[];
extern char NCL_defalt[];
extern char NCL_warn[];
extern char NCL_nowarn[];
extern char NCL_wrap[]; 
extern char NCL_projct[];
extern char NCL_start[];
extern char NCL_middle[];
extern char NCL_lock[];
extern char NCL_interp[];
extern char NCL_smooth[];
extern char NCL_off[];
extern char NCL_auto[];
extern char NCL_fmill[];
extern char NCL_height[];
extern char NCL_pass[];
extern char NCL_rapto[];
extern char NCL_xyplan[];
extern char NCL_yzplan[];
extern char NCL_zxplan[];
extern char NCL_smill[];

extern char NCL_box[];
extern char NCL_cone[];
extern char NCL_cylinder[];
extern char NCL_sphere[];
extern char NCL_torus[];
extern char NCL_extrud[];
extern char NCL_level[];
extern char NCL_prof[];
extern char NCL_load[];
extern char NCL_trform[];
extern char NCL_save[];
extern char NCL_fixtur[];
extern char NCL_bound[];
extern char NCL_stl[];

#endif

#define NCL_NKEYWD 

#endif
