//
//     MODULE NAME AND RELEASE LEVEL
//       toolibres.h , 25.4
//    DATE AND TIME OF LAST  MODIFICATION
//       12/08/15 , 14:02:38
//
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by toolib.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_CHILD1                      101
#define IDD_CHILD2                      102
#define IDD_CHILD3                      103
#define IDD_CHILD4                      104
#define IDR_MAINFRAME                   128
#define IDR_TOOLIBTYPE                  129
#define IDC_EDIT1                       130
#define IDC_DISP_SYMBOL                 131
#define IDC_RADIO1                      132
#define IDC_DISP_DRAW                   133
#define IDC_RADIO2                      134
#define IDC_RADIO3                      135
#define IDC_GROUPBOX1                   136
#define IDD_PROMPT                      138
#define IDD_DEFINEDLG                   139
#define IDD_CUTDLG                      140
#define IDD_COMDLG                      141
#define IDD_MODLIST                     142
#define IDD_PARMS                       143
#define IDD_OPERATE                     144
#define IDD_FILEOPEN_DLG                146
#define IDD_FIND_DIALOG                 147
#define IDD_TOOL_DISPLAY                148
#define IDD_TEXTWIN2                    149
#define IDC_DIALOG_PANE                 150
#define IDC_ADD                         1000
#define IDC_DELETE                      1001
#define IDC_SEARCH                      1002
#define IDC_CUTTYPE                     1005
#define IDC_EDIT_TOOL                   1006
#define IDC_EDIT_DEF1                   1007
#define IDC_CHECK1                      1008
#define IDC_CUTTER                      1008
#define IDC_HEADING                     1008
#define IDC_SYMBOL_CK                   1008
#define IDC_CUT_DEFINE                  1009
#define IDC_SHANK_CK                    1009
#define IDC_EDIT_PARM1                  1010
#define IDC_DISP_SEG                    1010
#define IDC_EDIT_DEF2                   1011
#define IDC_DISP_HOLD                   1011
#define IDC_EDIT_PARM2                  1012
#define IDC_DISP_MOV                    1012
#define IDC_COMBO4                      1013
#define IDC_SHADE                       1013
#define IDC_DISP_PNT                    1014
#define IDC_HOLDER_CK                   1014
#define IDC_DISP_LOAD                   1015
#define IDC_DISP_DEFINE                 1016
#define IDC_EDIT_DEF3                   1017
#define IDC_EDIT_PARM3                  1018
#define IDC_TOOL_LIST                   1018
#define IDC_EDIT_DEF4                   1019
#define IDC_EDIT_PARM4                  1020
#define IDC_EDIT_DEF5                   1021
#define IDC_EDIT_PARM5                  1022
#define IDC_EDIT_DEF6                   1023
#define IDC_EDIT_PARM6                  1024
#define IDC_METAFILE                    1025
#define IDC_BROWSE1                     1026
#define IDC_EDIT_DEF7                   1027
#define IDC_EDIT_PARM7                  1028
#define IDC_PROMPT_MSG                  1029
#define IDC_INPUT                       1030
#define IDC_EDIT_DESP                   1031
#define IDC_BROWSE                      1032
#define IDC_EDIT2                       1033
#define IDC_EDIT3                       1034
#define IDC_EDIT4                       1035
#define IDC_EDIT5                       1036
#define IDC_EDIT6                       1037
#define IDC_STATIC1                     1038
#define IDC_EDIT7                       1039
#define IDC_STATIC3                     1040
#define IDC_EDIT8                       1041
#define IDC_STATIC2                     1042
#define IDC_EDIT9                       1043
#define IDC_STATIC4                     1044
#define IDC_STATIC5                     1045
#define IDC_STATIC6                     1046
#define IDC_STATIC7                     1047
#define IDC_TOOLNUM                     1048
#define IDC_CUTPARM                     1049
#define IDC_PCUT                        1050
#define IDC_DISP                        1051
#define IDC_LTOOL                       1052
#define IDC_EDIT10                      1053
#define IDC_PSYMBOL                     1053
#define IDC_PSHANK                      1054
#define IDC_OPT_COMMAND                 1055
#define IDC_EDIT11                      1056
#define IDC_PHOLDER                     1056
#define IDC_FDLG_SYSDIR                 1057
#define IDC_PARAM_LABEL                 1058
#define IDC_EDIT12                      1059
#define IDC_EDIT13                      1060
#define IDC_FDLG_LOCDIR                 1061
#define IDC_EDIT14                      1062
#define IDC_Symbol                      1063
#define IDC_EDIT15                      1064
#define IDC_TOOLDRAW                    1065
#define IDC_EDIT16                      1066
#define IDC_SEARCH_STRING               1067
#define IDC_EDIT17                      1068
#define IDC_EDIT18                      1069
#define IDD_TOOL_FIND                   1070
#define IDC_EDIT19                      1071
#define IDC_EDIT20                      1072
#define IDC_SHANK_TEXT                  1073
#define IDC_EDIT21                      1074
#define IDC_EDIT22                      1075
#define IDC_EDIT23                      1076
#define IDC_EDIT24                      1077
#define IDC_EDIT25                      1078
#define IDC_EDIT26                      1079
#define IDC_EDIT27                      1080
#define IDC_EDIT28                      1081
#define IDC_EDIT29                      1082
#define IDC_EDIT30                      1083
#define IDC_EDIT31                      1084
#define IDC_EDIT32                      1085
#define IDC_EDIT33                      1086
#define IDC_EDIT34                      1087
#define IDC_EDIT35                      1088
#define IDC_EDIT36                      1089
#define IDC_EDIT37                      1090
#define IDC_EDIT38                      1091
#define IDC_EDIT39                      1092
#define IDC_EDIT40                      1093
#define IDC_EDIT41                      1094
#define IDC_FDLG_FOLDER                 1095
#define IDC_BROWSE2                     1096
#define IDC_FDLG_FNAME                  1152
#define IDC_SYMBOL_BUTTON               1153
#define IDC_SHANK_BUTTON                1154
#define IDC_HOLDER_BUTTON               1155
#define IDC_SYLBOL_NAME                 1156
#define IDC_SHANK_NAME                  1157
#define IDC_HOLDER_NAME                 1158
#define IDC_SYMBOL_LIB                  1159
#define IDC_SYMBOL_NAME                 1160
#define IDC_SHADE_CHC                   1162
#define IDC_LIST_PROF                   1163
#define IDC_CLASS                       1164
#define IDC_CLASHES_CHC                 1165
#define IDC_TOOL_TLIST                  1166
#define IDC_LIST_PROF2                  1166
#define IDC_LIST_SYMBOLS                1166
#define IDC_TEXTWINLABEL                1167
#define IDC_TEXTWINEDIT                 1168
#define ID_FILTER_TLIST                 1199
#define ID_FILE_LOAD                    32771
#define ID_FILE_DEFINE                  32773
#define ID_STATUS_STATUS                32774
#define ID_LIST_BRIEF                   32777
#define ID_LIST_FULL                    32778
#define ID_LIST_MODIFY                  32779
#define ID_DESCRIPTIONS_PARAMETERS      32780
#define ID_DESCRIPTIONS_OPERATORMESSAGE 32781
#define ID_EDIT_ADD                     32782
#define ID_EDIT_SEARCH                  32783
#define ID_EDIT_DELETE                  32784
#define IDC_FILE_SAVE                   32785
#define ID_HELP_HELP                    32786
#define ID_FILE_PROPERTIES              32787
#define ID_FILE_INIT                    32788
#define IDC_ABOUTLABEL1                 61220
#define IDC_ABOUTLABEL2                 61221
#define IDC_SHANK_CHECK                 61233

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1201
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
