/*********************************************************************
**    NAME         :  lipvstubs.c
**
**       CONTAINS:
**				Stub definitions for platforms that do not support NCLIPV.
**
**    COPYRIGHT 2001 (c) NCCS, Inc.  All Rights Reserved.
**
**    MODULE NAME AND RELEASE LEVEL 
**       lipvstubs.c , 25.1
**    DATE AND TIME OF LAST MODIFICATION
**       04/29/15 , 15:11:17
**
*********************************************************************/
#ifndef UU_IPV
void LiAllocate() {}
void LiAttributeClassCreate() {}
void LiBackgroundSet() {}
void LiBrBodyGetFirstFace() {}
void LiBrBodyQueryCreate() {}
void LiBrBodyQueryDestroy() {}
void LiBrFaceGetFirstLoop() {}
void LiBrFaceGetNextFace() {}
void LiBrFaceGetPlaneEquation() {}
void LiBrLoopEdgeGetFinishVertex() {}
void LiBrLoopEdgeGetNextLoopEdge() {}
void LiBrLoopEdgeGetStartVertex() {}
void LiBrLoopGetFirstLoopEdge() {}
void LiBrLoopGetNextLoop() {}
void LiBrVertexGetPosition() {}
void LiCallBackSet() {}
void LiColourInitialise() {}
void LiComparisonCreate() {}
void LiComparisonDestroy() {}
void LiControlSet() {}
void LiCutNumberGet() {}
void LiCutNumberSet() {}
void LiDataGetBoolean() {}
void LiDataGetColour() {}
void LiDataGetDouble() {}
void LiDataGetDoubleBounds() {}
void LiDataGetEnum() {}
void LiDataGetGenericPtr() {}
void LiDataGetNat32() {}
void LiDataSetBitfield() {}
void LiDataSetBoolean() {}
void LiDataSetDoubleBounds() {}
void LiDataSetColour() {}
void LiDataSetDouble() {}
void LiDataSetDoublePtr() {}
void LiDataSetEnum() {}
void LiDataSetFloat() {}
void LiDataSetGenericPtr() {}
void LiDataSetNat32() {}
void LiDataSetPoint() {}
void LiDataSetString() {}
void LiDeallocate() {}
void LiDrawableCopyToImage() {}
void LiDrawableDestroy() {}
void LiDrawableProjectImageToWorld() {}
void LiDrawableProjectWorldToImage() {}
void LiDrawableRender() {}
void LiDrawableSetProperty() {}
void LiDriverFindFromName() {}
void LiDriverResizeNotify() {}
void LiDriverSet() {}
void LiDriverSetControl() {}
void LiExecute() {}
void LiFileClose() {}
void LiFileOpen() {}
void LiImageCreate() {}
void LiImageDestroy() {}
void LiImageGetPixel() {}
void LiImageAllocateData() {}
void LiImageSetDepth() {}
void LiImageSetWidth() {}
void LiImageSetHeight() {}
void LiInitialise() {}
void LiLightListSet() {}
void LiLineStyleCreate() {}
void LiLineStyleSetProperty() {}
void LiMachiningSessionAddPrims() {}
void LiMachiningSessionCreate() {}
void LiMachiningSessionDestroy() {}
void LiMachiningSessionRemovePrims() {}
void LiMachiningSessionSet() {}
void LiMaterialCreate() {}
void LiMaterialDestroy() {}
void LiMaterialSetColour() {}
void LiMaterialSetShader() {}
void LiMoViewSet() {}
void LiMWEnvironmentDestroy() {}
void LiMWEnvironmentRestore() {}
void LiMWEnvironmentSave() {}
void LiMWUSolidCreateFromSTLFile() {}
void LiMWUSolidSaveToSTLFile() {}
void LiMWUViewportCreate() {}
void LiMWUViewportDestroy() {}
void LiMWUViSolidRestoreFromFile() {}
void LiMWUViSolidSaveToFile() {}
void LiMWViewportAutoClipping() {}
void LiMWViewportCreate() {}
void LiMWViewportDestroy() {}
void LiMWViewportSetLightList() {}
void LiMWViewportSetPrimProperty() {}
void LiMWViewportSetProperty() {}
void LiMWViewportSetSessPrimProperty() {}
void LiOGLDrvImageInitialise() {}
void LiOGLDrvImageSetCurrent() {}
void LiOGLDrvImageTerminate() {}
void LiOGLDrvWindowInitialise() {}
void LiOGLDrvWindowSetCurrent() {}
void LiPointInitialise() {}
void LiPolycurveAddLine() {}
void LiPolycurveEnd() {}
void LiPrimitiveCopy() {}
void LiPrimitiveCreateBallEndTool() {}
void LiPrimitiveCreateBoxSolid() {}
void LiPrimitiveCreateBullNoseTool() {}
void LiPrimitiveCreateExtrudedSolid() {}
void LiPrimitiveCreateFlatEndTool() {}
void LiPrimitiveCreatePolycurve() {}
void LiPrimitiveCreatePolygonHolder() {}
void LiPrimitiveCreatePolygonTool() {}
void LiPrimitiveCreateRotatedSolid() {}
void LiPrimitiveCreateText() {}
void LiPrimitiveCreateTool() {}
void LiPrimitiveCreateToolHolder() {}
void LiPrimitiveCreateTriangleSolid() {}
void LiPrimitiveCreateTurningTool() {}
void LiPrimitiveCreateTurningHolder() {}
void LiPrimitiveDestroy() {}
void LiPrimitiveGetContents() {}
void LiPrimitiveGetRenObjProperty() {}
void LiPrimitiveGetSessionPrim() {}
void LiPrimitiveGetSolidClosure() {}
void LiPrimitiveGetSolidMesh() {}
void LiPrimitiveGetSolidProperty() {}
void LiPrimitiveGetSolidType() {}
void LiPrimitiveGetVisualProperty() {}
void LiPrimitiveReferenceAppend() {}
void LiPrimitiveReferenceCreate() {}
void LiPrimitiveReferenceDestroy() {}
void LiPrimitiveSetClashMaterial() {}
void LiPrimitiveSetCutMaterial() {}
void LiPrimitiveSetInteractType() {}
void LiPrimitiveSetMaterial() {}
void LiPrimitiveSetRenObjProperty() {}
void LiPrimitiveSetSolidProperty() {}
void LiPrimitiveSetSolidTransform() {}
void LiPrimitiveSetSolidType() {}
void LiPrimitiveSetVisualProperty() {}
void LiPrimitiveSolidExtract() {}
void LiPrimitiveSolidUnion() {}
void LiProfileAddLine() {}
void LiProfileCreate() {}
void LiProfileDestroy() {}
void LiProgressGetProperty() {}
void LiRegionOfInterestSet() {}
void LiRvDefineComparison() {}
void LiRvDoLinearCut() {}
void LiRvPickExecute() {}
void LiRvPickGetResult() {}
void LiRvPickVisual() {}
void LiRvSolidGetVolume() {}
void LiRvStockSection() {}
void LiRvToolAttachHolder() {}
void LiRvToolDoLinearCut() {}
void LiRvToolSelect() {}
void LiRvToolSetPosition() {}
void LiSelfIntersectionListDestroy() {}
void LiSelfIntersectionListGetFirst() {}
void LiSessionAddPrim() {}
void LiSessionCreate() {}
void LiSessionDestroy() {}
void LiSessionGetProperty() {}
void LiSessionPrimGetProperty() {}
void LiSessionPrimGetVisualProperty() {}
void LiSessionPrimitiveSetVisualProperty() {}
void LiSessionPrimSetInteractType() {}
void LiSessionPrimSetProperty() {}
void LiSessionPrimSetVisualProperty() {}
void LiSessionRemovePrim() {}
void LiSessionSetProperty() {}
void LiShaderCreate() {}
void LiShaderDestroy() {}
void LiShaderListCreate() {}
void LiShaderReferenceCreate() {}
void LiShaderReferenceDestroy() {}
void LiShaderSetArg() {}
void LiShaderSetColour() {}
void LiSOBodyGetFirstPatch() {}
void LiSOEntityGetProperty() {}
void LiSOFaceGetFirstLoop() {}
void LiSOFaceGetNextFace() {}
void LiSolidStyleCreate() {}
void LiSolidStyleDestroy() {}
void LiSolidStyleSetProperty() {}
void LiSOLoopGetFirstLoopEdge() {}
void LiSOLoopEdgeGetEndVertex() {}
void LiSOLoopEdgeGetNextOnFace() {}
void LiSOLoopEdgeGetSEdge() {}
void LiSOLoopEdgeGetStartVertex() {}
void LiSOLoopGetNextLoop() {}
void LiSOPatchGetFirstFace() {}
void LiSOPatchGetNextPatch() {}
void LiSOSelfIntersectionListDestroy() {}
void LiSOSelfIntersectionListGetFirst() {}
void LiSOSessionBegin() {}
void LiSOSessionEnd() {}
void LiSOSolidClose() {}
void LiSOSolidFixSelfIntersections() {}
void LiSOSolidGetBody() {}
void LiSOSolidGetSelfIntersections() {}
void LiSOSolidMakeConsistent() {}
void LiSOSolidMergeCoplanarFaces() {}
void LiSOSolidPrepareSinglePrecision() {}
void LiSOSolidStore() {}
void LiSOVertexGetPosition() {}
void LiTerminate() {}
void LiTextStyleCreate() {}
void LiTextStyleSetProperty() {}
void LiTransformConcatenate() {}
void LiTransformCopy() {}
void LiTransformCreate() {}
void LiTransformDefine() {}
void LiTransformDestroy() {}
void LiTransformScale() {}
void LiTriangleSolidAddFace() {}
void LiTriangleSolidEnd() {}
void LiVectorInitialise() {}
void LiViAllowCutType() {}
void LiViAssemblyAddSolid() {}
void LiViAssemblyCreate() {}
void LiViAssemblyDestroy() {}
void LiViAssemblyRemoveSolid() {}
void LiViAssemblySetParent() {}
void LiViBodyGetFirstFace() {}
void LiViDefineComparison() {}
void LiViDirtyAreaSet() {}
void LiViEntityGetAttribute() {}
void LiViEntityGetPrimitive() {}
void LiViEntityGetSessionPrim() {}
void LiViEntitySetAttribute() {}
void LiViewCreate() {}
void LiViewDestroy() {}
void LiViewGet() {}
void LiViewGetPinhole() {}
void LiViewProjectImageToWorld() {}
void LiViewSetClipping() {}
void LiViewSetMatrices() {}
void LiViewSetPinhole() {}
void LiViewSetResolution() {}
void LiViFaceGetCutNumber() {}
void LiViFaceGetFirstLoop() {}
void LiViFaceGetMaterial() {}
void LiViFaceGetNextFace() {}
void LiViFaceGetPlaneEquation() {}
void LiViFaceGetSurfaceFaces() {}
void LiViGetPredefinedAttributeClass() {}
void LiViLatheAddSolid() {}
void LiViLatheCreate() {}
void LiViLatheDestroy() {}
void LiViLatheRotate() {}
void LiViLatheSetAxes() {}
void LiViLatheSetOrientation() {}
void LiViLatheStart() {}
void LiViLatheStop() {}
void LiViLoopEdgeGetFinishVertex() {}
void LiViLoopEdgeGetNextLoopEdge() {}
void LiViLoopEdgeGetStartVertex() {}
void LiViLoopGetFirstLoopEdge() {}
void LiViLoopGetNextLoop() {}
void LiViPerformCut() {}
void LiViPickedEntityExpand() {}
void LiViPickedEntityGetNext() {}
void LiViPickedEntityGetSurface() {}
void LiViPickedEntityListDestroy() {}
void LiViPickedEntityListGetFirst() {}
void LiViRenderObjectSetPosition() {}
void LiViSolidCreateDifference() {}
void LiViSolidCreateSlice() {}
void LiViSolidGetAxes() {}
void LiViSolidGetBody() {}
void LiViSolidGetIntersectSolid() {}
void LiViSolidGetNumParts() {}
void LiViSolidGetPosition() {}
void LiViSolidGetProgrammingCoordSys() {}
void LiViSolidGetVolume() {}
void LiViSolidMultipleRotate() {}
void LiViSolidMultipleTranslate() {}
void LiViSolidPairSetInteractType() {}
void LiViSolidPick() {}
void LiViSolidRotate() {}
void LiViSolidSection() {}
void LiViSolidSetAxes() {}
void LiViSolidSetEnabled() {}
void LiViSolidSetPosition() {}
void LiViSolidSetProgrammingCoordSys() {}
void LiViSolidSplit() {}
void LiViSolidSubtract() {}
void LiViSolidTranslate() {}
void LiViSolidUnion() {}
void LiViSolidUnsplit() {}
void LiViToolAttachHolder() {}
void LiViToolDefine5AxisLinearCut() {}
void LiViToolDefineComplexCut() {}
void LiViToolDoArcCut() {}
void LiViToolDoVerticalArcCut() {}
void LiViToolGetAxis() {}
void LiViToolGetPosition() {}
void LiViToolSelect() {}
void LiViToolSetAxis() {}
void LiViToolSetPosition() {}
void LiViTurningToolDoLinearCut() {}
void LiViTurningToolDoSmoothArcCut() {}
void LiViTurningToolDoSmoothLinearCut() {}
void LiViTurningToolSelect() {}
void LiViUniverseSet() {}
void LiViVertexGetPosition() {}



#endif
